### ISSUE TITLE
Installation problem 

### ISSUE THREAD

**Issue by oxerael** [chaiNNer-org/chaiNNer#1776]
**Information:**

- Chainner version: 
- OS: Windows, 0.16.1 x64

**Description**
This Error occurs at the end of installation process

**Logs**
[2023-05-03 19:40:07.133] [info]  Attempting to check for a port...
[2023-05-03 19:40:07.156] [info]  Port found: 8000
[2023-05-03 19:40:07.414] [info]  Attempting to check Python env...
[2023-05-03 19:40:07.417] [info]  Integrated Python not found at C:\Users\israel\AppData\Roaming\chaiNNer\python\python\python.exe
[2023-05-03 19:40:07.417] [info]  Downloading integrated Python...
[2023-05-03 19:40:11.820] [info]  Extracting integrated Python...
[2023-05-03 19:40:34.839] [info]  Removing downloaded files...
[2023-05-03 19:40:35.024] [info]  Final Python binary: C:\Users\israel\AppData\Roaming\chaiNNer\python\python\python.exe
[2023-05-03 19:40:35.025] [info]  {
  python: 'C:\\Users\\israel\\AppData\\Roaming\\chaiNNer\\python\\python\\python.exe',
  version: '3.9.7'
}
[2023-05-03 19:40:35.285] [info]  Attempting to check Ffmpeg env...
[2023-05-03 19:40:35.287] [info]  Integrated FFMPEG not found at C:\Users\israel\AppData\Roaming\chaiNNer\ffmpeg\ffmpeg.exe
[2023-05-03 19:40:35.287] [info]  Downloading integrated FFMPEG...
[2023-05-03 19:40:41.190] [info]  Extracting integrated FFMPEG...
[2023-05-03 19:40:47.003] [info]  Removing downloaded files...
[2023-05-03 19:40:47.018] [info]  Final ffmpeg binary: C:\Users\israel\AppData\Roaming\chaiNNer\ffmpeg\ffmpeg.exe
[2023-05-03 19:40:47.019] [info]  Final ffprobe binary: C:\Users\israel\AppData\Roaming\chaiNNer\ffmpeg\ffprobe.exe
[2023-05-03 19:40:47.279] [info]  Attempting to check Python deps...
[2023-05-03 19:40:47.280] [info]  Python executable: C:\Users\israel\AppData\Roaming\chaiNNer\python\python\python.exe
[2023-05-03 19:40:47.281] [info]  Running pip command: pip list --format=json --disable-pip-version-check
[2023-05-03 19:40:50.683] [info]  Installing/Updating dependencies...
[2023-05-03 19:40:50.685] [info]  Python executable: C:\Users\israel\AppData\Roaming\chaiNNer\python\python\python.exe
[2023-05-03 19:40:50.685] [info]  Running pip command: pip install --upgrade sanic==21.9.3 Sanic-Cors==1.0.1 opencv-python==4.6.0.66 numpy==1.23.2 Pillow==9.2.0 appdirs==1.4.4 ffmpeg-python==0.2.0 pywin32==304 --disable-pip-version-check
[2023-05-03 19:41:08.835] [error]   WARNING: The script sanic.exe is installed in 'C:\Users\israel\AppData\Roaming\chaiNNer\python\python\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[2023-05-03 19:41:19.089] [error]   WARNING: The script f2py.exe is installed in 'C:\Users\israel\AppData\Roaming\chaiNNer\python\python\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[2023-05-03 19:41:36.643] [info]  Attempting to spawn backend...
[2023-05-03 19:41:36.655] [info]  Successfully spawned backend.
[2023-05-03 19:41:38.644] [error] Backend: Traceback (most recent call last):
  File "C:\Users\israel\Desktop\Nova pasta (3)\resources\src\run.py", line 14, in <module>

[2023-05-03 19:41:38.645] [error] Backend:     from sanic import Sanic
  File "C:\Users\israel\AppData\Roaming\chaiNNer\python\python\lib\site-packages\sanic\__init__.py", line 2, in <module>
    from sanic.app import Sanic
  File "C:\Users\israel\AppData\Roaming\chaiNNer\python\python\lib\site-packages\sanic\app.py", line 77, in <module>
    from sanic.server.protocols.websocket_protocol import WebSocketProtocol
  File "C:\Users\israel\AppData\Roaming\chaiNNer\python\python\lib\site-packages\sanic\server\protocols\websocket_protocol.py", line 3, in <module>

[2023-05-03 19:41:38.646] [error] Backend:     from websockets.connection import CLOSED, CLOSING, OPEN
ImportError: cannot import name 'CLOSED' from 'websockets.connection' (C:\Users\israel\AppData\Roaming\chaiNNer\python\python\lib\site-packages\websockets\connection.py)

[2023-05-03 19:41:38.704] [error] Python subprocess exited with code 1 and signal null
[2023-05-03 19:43:58.602] [info]  Attempting to kill backend...
[2023-05-03 19:43:58.604] [error] Error killing backend.
[2023-05-03 19:43:58.605] [info]  Cleaning up temp folders...
[2023-05-03 19:44:11.851] [info]  Attempting to check for a port...
[2023-05-03 19:44:11.872] [info]  Port found: 8000
[2023-05-03 19:44:12.142] [info]  Attempting to check Python env...
[2023-05-03 19:44:12.194] [info]  Final Python binary: C:\Users\israel\AppData\Roaming\chaiNNer\python\python\python.exe
[2023-05-03 19:44:12.195] [info]  {
  python: 'C:\\Users\\israel\\AppData\\Roaming\\chaiNNer\\python\\python\\python.exe',
  version: '3.9.7'
}
[2023-05-03 19:44:12.455] [info]  Attempting to check Ffmpeg env...
[2023-05-03 19:44:12.456] [info]  Final ffmpeg binary: C:\Users\israel\AppData\Roaming\chaiNNer\ffmpeg\ffmpeg.exe
[2023-05-03 19:44:12.457] [info]  Final ffprobe binary: C:\Users\israel\AppData\Roaming\chaiNNer\ffmpeg\ffprobe.exe
[2023-05-03 19:44:12.721] [info]  Attempting to check Python deps...
[2023-05-03 19:44:12.723] [info]  Python executable: C:\Users\israel\AppData\Roaming\chaiNNer\python\python\python.exe
[2023-05-03 19:44:12.723] [info]  Running pip command: pip list --format=json --disable-pip-version-check
[2023-05-03 19:44:13.987] [info]  Attempting to spawn backend...
[2023-05-03 19:44:13.994] [info]  Successfully spawned backend.
[2023-05-03 19:44:14.600] [error] Backend: Traceback (most recent call last):
  File "C:\Users\israel\Desktop\Nova pasta (3)\resources\src\run.py", line 14, in <module>

[2023-05-03 19:44:14.601] [error] Backend:     from sanic import Sanic
  File "C:\Users\israel\AppData\Roaming\chaiNNer\python\python\lib\site-packages\sanic\__init__.py", line 2, in <module>
    from sanic.app import Sanic
  File "C:\Users\israel\AppData\Roaming\chaiNNer\python\python\lib\site-packages\sanic\app.py", line 77, in <module>
    from sanic.server.protocols.websocket_protocol import WebSocketProtocol
  File "C:\Users\israel\AppData\Roaming\chaiNNer\python\python\lib\site-packages\sanic\server\protocols\websocket_protocol.py", line 3, in <module>
    from websockets.connection import CLOSED, CLOSING, OPEN
ImportError: cannot import name 'CLOSED' from 'websockets.connection' (C:\Users\israel\AppData\Roaming\chaiNNer\python\python\lib\site-packages\websockets\connection.py)

[2023-05-03 19:44:14.655] [error] Python subprocess exited with code 1 and signal null
[2023-05-03 19:49:13.952] [info]  Attempting to kill backend...
[2023-05-03 19:49:13.954] [error] Error killing backend.
[2023-05-03 19:49:13.955] [info]  Cleaning up temp folders...
[2023-05-03 19:50:32.807] [info]  Attempting to check for a port...
[2023-05-03 19:50:32.841] [info]  Port found: 8000
[2023-05-03 19:50:33.094] [info]  Attempting to check Python env...
[2023-05-03 19:50:33.342] [info]  Final Python binary: C:\Users\israel\AppData\Roaming\chaiNNer\python\python\python.exe
[2023-05-03 19:50:33.343] [info]  {
  python: 'C:\\Users\\israel\\AppData\\Roaming\\chaiNNer\\python\\python\\python.exe',
  version: '3.9.7'
}
[2023-05-03 19:50:33.606] [info]  Attempting to check Ffmpeg env...
[2023-05-03 19:50:33.608] [info]  Final ffmpeg binary: C:\Users\israel\AppData\Roaming\chaiNNer\ffmpeg\ffmpeg.exe
[2023-05-03 19:50:33.608] [info]  Final ffprobe binary: C:\Users\israel\AppData\Roaming\chaiNNer\ffmpeg\ffprobe.exe
[2023-05-03 19:50:33.868] [info]  Attempting to check Python deps...
[2023-05-03 19:50:33.870] [info]  Python executable: C:\Users\israel\AppData\Roaming\chaiNNer\python\python\python.exe
[2023-05-03 19:50:33.871] [info]  Running pip command: pip list --format=json --disable-pip-version-check
[2023-05-03 19:50:34.999] [info]  Attempting to spawn backend...
[2023-05-03 19:50:35.008] [info]  Successfully spawned backend.
[2023-05-03 19:50:35.780] [error] Backend: Traceback (most recent call last):
  File "C:\Users\israel\AppData\Local\chainner\app-0.16.1\resources\src\run.py", line 14, in <module>

[2023-05-03 19:50:35.781] [error] Backend:     from sanic import Sanic
  File "C:\Users\israel\AppData\Roaming\chaiNNer\python\python\lib\site-packages\sanic\__init__.py", line 2, in <module>
    from sanic.app import Sanic
  File "C:\Users\israel\AppData\Roaming\chaiNNer\python\python\lib\site-packages\sanic\app.py", line 77, in <module>
    from sanic.server.protocols.websocket_protocol import WebSocketProtocol
  File "C:\Users\israel\AppData\Roaming\chaiNNer\python\python\lib\site-packages\sanic\server\protocols\websocket_protocol.py", line 3, in <module>
    from websockets.connection import CLOSED, CLOSING, OPEN
ImportError: cannot import name 'CLOSED' from 'websockets.connection' (C:\Users\israel\AppData\Roaming\chaiNNer\python\python\lib\site-packages\websockets\connection.py)

[2023-05-03 19:50:35.846] [error] Python subprocess exited with code 1 and signal null

**Comment by joeyballentine** [comment]
Are you using the latest version?

**Comment by guanchv** [comment]
I have the same issue while installing.
[2023-05-27 01:29:58.274] [info]  Attempting to check for a port...
[2023-05-27 01:29:58.287] [info]  Port found: 8000
[2023-05-27 01:29:58.542] [info]  Attempting to check Python env...
[2023-05-27 01:29:58.543] [info]  Integrated Python not found at C:\Users\barri\AppData\Roaming\chaiNNer\python\python\python.exe
[2023-05-27 01:29:58.543] [info]  Downloading integrated Python...
[2023-05-27 01:30:19.253] [info]  Extracting integrated Python...
[2023-05-27 01:30:23.501] [info]  Removing downloaded files...
[2023-05-27 01:30:23.634] [info]  Final Python binary: C:\Users\barri\AppData\Roaming\chaiNNer\python\python\python.exe
[2023-05-27 01:30:23.635] [info]  {
  python: 'C:\\Users\\barri\\AppData\\Roaming\\chaiNNer\\python\\python\\python.exe',
  version: '3.9.7'
}
[2023-05-27 01:30:23.902] [info]  Attempting to check Ffmpeg env...
[2023-05-27 01:30:23.903] [info]  Integrated FFMPEG not found at C:\Users\barri\AppData\Roaming\chaiNNer\ffmpeg\ffmpeg.exe
[2023-05-27 01:30:23.904] [info]  Downloading integrated FFMPEG...
[2023-05-27 01:30:51.406] [info]  Extracting integrated FFMPEG...
[2023-05-27 01:30:52.690] [info]  Removing downloaded files...
[2023-05-27 01:30:52.697] [info]  Final ffmpeg binary: C:\Users\barri\AppData\Roaming\chaiNNer\ffmpeg\ffmpeg.exe
[2023-05-27 01:30:52.698] [info]  Final ffprobe binary: C:\Users\barri\AppData\Roaming\chaiNNer\ffmpeg\ffprobe.exe
[2023-05-27 01:30:52.953] [info]  Attempting to check Python deps...
[2023-05-27 01:30:52.953] [info]  Python executable: C:\Users\barri\AppData\Roaming\chaiNNer\python\python\python.exe
[2023-05-27 01:30:52.954] [info]  Running pip command: pip list --format=json --disable-pip-version-check
[2023-05-27 01:30:54.649] [info]  Installing/Updating dependencies...
[2023-05-27 01:30:54.650] [info]  Python executable: C:\Users\barri\AppData\Roaming\chaiNNer\python\python\python.exe
[2023-05-27 01:30:54.650] [info]  Running pip command: pip install --upgrade sanic==21.9.3 Sanic-Cors==1.0.1 opencv-python==4.6.0.66 numpy==1.23.2 Pillow==9.2.0 appdirs==1.4.4 ffmpeg-python==0.2.0 pywin32==304 --disable-pip-version-check
[2023-05-27 01:31:35.787] [error]   WARNING: The script sanic.exe is installed in 'C:\Users\barri\AppData\Roaming\chaiNNer\python\python\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[2023-05-27 01:31:40.739] [error]   WARNING: The script f2py.exe is installed in 'C:\Users\barri\AppData\Roaming\chaiNNer\python\python\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[2023-05-27 01:31:49.563] [info]  Attempting to spawn backend...
[2023-05-27 01:31:49.568] [info]  Successfully spawned backend.
[2023-05-27 01:31:50.377] [error] Backend: Traceback (most recent call last):
  File "C:\chaiNNer-windows-x64-0.16.1\resources\src\run.py", line 14, in <module>

[2023-05-27 01:31:50.377] [error] Backend:     from sanic import Sanic
  File "C:\Users\barri\AppData\Roaming\chaiNNer\python\python\lib\site-packages\sanic\__init__.py", line 2, in <module>
    from sanic.app import Sanic
  File "C:\Users\barri\AppData\Roaming\chaiNNer\python\python\lib\site-packages\sanic\app.py", line 77, in <module>
    from sanic.server.protocols.websocket_protocol import WebSocketProtocol
  File "C:\Users\barri\AppData\Roaming\chaiNNer\python\python\lib\site-packages\sanic\server\protocols\websocket_protocol.py", line 3, in <module>
    from websockets.connection import CLOSED, CLOSING, OPEN
ImportError: cannot import name 'CLOSED' from 'websockets.connection' (C:\Users\barri\AppData\Roaming\chaiNNer\python\python\lib\site-packages\websockets\connection.py)

[2023-05-27 01:31:50.404] [error] Python subprocess exited with code 1 and signal null
[2023-05-27 01:33:31.533] [info]  Attempting to kill backend...
[2023-05-27 01:33:31.534] [error] Error killing backend.
[2023-05-27 01:33:31.535] [info]  Cleaning up temp folders...
[2023-05-27 01:33:38.101] [info]  Attempting to check for a port...
[2023-05-27 01:33:38.112] [info]  Port found: 8000
[2023-05-27 01:33:38.363] [info]  Attempting to check Python env...
[2023-05-27 01:33:38.394] [info]  Final Python binary: C:\Users\barri\AppData\Roaming\chaiNNer\python\python\python.exe
[2023-05-27 01:33:38.394] [info]  {
  python: 'C:\\Users\\barri\\AppData\\Roaming\\chaiNNer\\python\\python\\python.exe',
  version: '3.9.7'
}
[2023-05-27 01:33:38.658] [info]  Attempting to check Ffmpeg env...
[2023-05-27 01:33:38.659] [info]  Final ffmpeg binary: C:\Users\barri\AppData\Roaming\chaiNNer\ffmpeg\ffmpeg.exe
[2023-05-27 01:33:38.659] [info]  Final ffprobe binary: C:\Users\barri\AppData\Roaming\chaiNNer\ffmpeg\ffprobe.exe
[2023-05-27 01:33:38.913] [info]  Attempting to check Python deps...
[2023-05-27 01:33:38.914] [info]  Python executable: C:\Users\barri\AppData\Roaming\chaiNNer\python\python\python.exe
[2023-05-27 01:33:38.914] [info]  Running pip command: pip list --format=json --disable-pip-version-check
[2023-05-27 01:33:39.728] [info]  Attempting to spawn backend...
[2023-05-27 01:33:39.738] [info]  Successfully spawned backend.
[2023-05-27 01:33:40.056] [error] Backend: Traceback (most recent call last):
  File "C:\chaiNNer-windows-x64-0.16.1\resources\src\run.py", line 14, in <module>

[2023-05-27 01:33:40.057] [error] Backend:     from sanic import Sanic
  File "C:\Users\barri\AppData\Roaming\chaiNNer\python\python\lib\site-packages\sanic\__init__.py", line 2, in <module>
    from sanic.app import Sanic
  File "C:\Users\barri\AppData\Roaming\chaiNNer\python\python\lib\site-packages\sanic\app.py", line 77, in <module>
    from sanic.server.protocols.websocket_protocol import WebSocketProtocol
  File "C:\Users\barri\AppData\Roaming\chaiNNer\python\python\lib\site-packages\sanic\server\protocols\websocket_protocol.py", line 3, in <module>
    from websockets.connection import CLOSED, CLOSING, OPEN
ImportError: cannot import name 'CLOSED' from 'websockets.connection' (C:\Users\barri\AppData\Roaming\chaiNNer\python\python\lib\site-packages\websockets\connection.py)

[2023-05-27 01:33:40.087] [error] Python subprocess exited with code 1 and signal null
[2023-05-27 01:57:30.031] [info]  Attempting to kill backend...
[2023-05-27 01:57:30.032] [error] Error killing backend.
[2023-05-27 01:57:30.032] [info]  Cleaning up temp folders...
[2023-05-27 01:57:47.281] [info]  Attempting to check for a port...
[2023-05-27 01:57:47.293] [info]  Port found: 8000
[2023-05-27 01:57:47.543] [info]  Attempting to check Python env...
[2023-05-27 01:57:47.929] [info]  Final Python binary: C:\Users\barri\AppData\Roaming\chaiNNer\python\python\python.exe
[2023-05-27 01:57:47.929] [info]  {
  python: 'C:\\Users\\barri\\AppData\\Roaming\\chaiNNer\\python\\python\\python.exe',
  version: '3.9.7'
}
[2023-05-27 01:57:48.182] [info]  Attempting to check Ffmpeg env...
[2023-05-27 01:57:48.183] [info]  Final ffmpeg binary: C:\Users\barri\AppData\Roaming\chaiNNer\ffmpeg\ffmpeg.exe
[2023-05-27 01:57:48.183] [info]  Final ffprobe binary: C:\Users\barri\AppData\Roaming\chaiNNer\ffmpeg\ffprobe.exe
[2023-05-27 01:57:48.436] [info]  Attempting to check Python deps...
[2023-05-27 01:57:48.437] [info]  Python executable: C:\Users\barri\AppData\Roaming\chaiNNer\python\python\python.exe
[2023-05-27 01:57:48.437] [info]  Running pip command: pip list --format=json --disable-pip-version-check
[2023-05-27 01:57:49.153] [info]  Attempting to spawn backend...
[2023-05-27 01:57:49.157] [info]  Successfully spawned backend.
[2023-05-27 01:57:49.451] [error] Backend: Traceback (most recent call last):
  File "C:\chaiNNer-windows-x64-0.16.1\resources\src\run.py", line 14, in <module>

[2023-05-27 01:57:49.452] [error] Backend:     from sanic import Sanic
  File "C:\Users\barri\AppData\Roaming\chaiNNer\python\python\lib\site-packages\sanic\__init__.py", line 2, in <module>
    from sanic.app import Sanic
  File "C:\Users\barri\AppData\Roaming\chaiNNer\python\python\lib\site-packages\sanic\app.py", line 77, in <module>
    from sanic.server.protocols.websocket_protocol import WebSocketProtocol
  File "C:\Users\barri\AppData\Roaming\chaiNNer\python\python\lib\site-packages\sanic\server\protocols\websocket_protocol.py", line 3, in <module>
    from websockets.connection import CLOSED, CLOSING, OPEN
ImportError: cannot import name 'CLOSED' from 'websockets.connection' (C:\Users\barri\AppData\Roaming\chaiNNer\python\python\lib\site-packages\websockets\connection.py)

[2023-05-27 01:57:49.480] [error] Python subprocess exited with code 1 and signal null

**Comment by joeyballentine** [comment]
@guanchv chaiNNer downloads its own python so you shouldn't need it installed on your MacBook. Are you sure you're having this same issue? (Same logs?) This issue should have been resolved a long time ago so on the latest version it should not be happening

**Comment by guanchv** [comment]
Well the thing is that on Windows I was using the wrong installation method. But in my mac book stays at "Loading main application..."

**Comment by guanchv** [comment]
Oh, I apologize. Just realized that I was following the link from a tutorial that was sending me to the 0.16.1 version. 
Just installed the lastest version and is working perfect. Thanks for your support!
