### ISSUE TITLE
Immediate critical error upon launching chaiNNer for the first time on Arch Linux

### ISSUE THREAD

**Issue by RecentRunner** [chaiNNer-org/chaiNNer#1809]
**Information:**

- Chainner version: [Alpha 0.18.7] also tried the 0.18.6 linux portables and the version from the [AUR](https://aur.archlinux.org/packages/chainner-bin) which should be the latest release
- OS: [Arch Linux x86_64, 6.3.2-arch1-1]

**Description**
I installed chainner, both through the AUR it didn't work, resulting in the screenshot below. I then tried running the linux portables in the release section both 0.18.7 and 0.18.6. No matter what I do I always get the same error shown below

![image](https://github.com/chaiNNer-org/chaiNNer/assets/10123690/3550d88e-ee99-4f68-9fb7-660f9649a5a2)

**Logs**
[main.log](https://github.com/chaiNNer-org/chaiNNer/files/11523626/main.log)

**Comment by joeyballentine** [comment]
I'll look into it a bit more later but at a first glance it looks like its trying to compile a bunch of the python dependencies and failing. I'm not sure why it's doing that but if i can figure anything out I'll let you know

**Comment by RecentRunner** [comment]
Okay so the issue resolved itself. I used `find` to search my computer for all mentions of chaiNNer I then manually deleted anything relating to the program and then installed the new version

Now the program is working perfectly. I guess the issue resolved itself in the update or perhaps the issue was with the clone repo in paru (My AUR manager)? I'm not too sure but thank you regardless 🥳 🎉

**Comment by guanchv** [comment]
Just installed the latest version but I'm having the same issue

**Comment by joeyballentine** [comment]
Have you tried doing the same thing that made it work before? Unfortunately I'm not sure how much help I can really be for this as I'm not a Linux user. Can you send your logs again?

**Comment by dcary94** [comment]
Having the same issue on a x64 Windows 11 - Any help would be greatly appreciated!
[main.log](https://github.com/chaiNNer-org/chaiNNer/files/11835022/main.log)

**Comment by joeyballentine** [comment]
Looks like there's an SSL issue causing pip to not be able to connect. Are you using a VPN or do you have strict firewall settings? @dcary94

**Comment by joeyballentine** [comment]
I'm not really sure to be honest, all i can see from your logs is that there is an SSL issue. I've never encountered that myself so I don't know what would be needed to get past that. 

The specific error is this:
```[error] WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))': /simple/sanic/```

Are you able to install from pip normally?

**Comment by dcary94** [comment]
I'm terribly sorry but I'm not sure what you mean by 'pip'?

Apologies

**Comment by joeyballentine** [comment]
Pip is python's package manager. ChaiNNer uses it to install the necessary python dependencies for its backend (which is why it can't start for you, since it's failing on that step)

**Comment by dcary94** [comment]
Great stuff! - Thanks for your help - I will speak to our IT team and see what they can do.

Really appreciate it!

**Comment by RafaelAmauri** [comment]
For anyone still having this issue on Arch Linux, if the error message you're getting in the terminal is something like 
```
12:42:02.054 › Error: /home/rafael/scripts/chaiNNer-linux-x64/python/python/bin/python3.9: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory
```

this means you need to install libcrypt. You can check this with pkgfile. It tells you what packages install what you need.

```
$ pkgfile -s libcrypt.so.1

core/libxcrypt-compat
extra/riscv64-linux-gnu-glibc
multilib/lib32-libxcrypt-compat
```

After installing libxcrypt-compat and lib32-libxcrypt-compat I was able to run chainner without issues :)

**Comment by rishabh4uh** [comment]
Hi, I'm still having the same issue, can someone please help me, will be grateful, attached the log file as well
[main.log](https://github.com/chaiNNer-org/chaiNNer/files/12572221/main.log)

**Comment by joeyballentine** [comment]
@rishabh4uh what version of chaiNNer is that? You're getting an error I've never seen before with one of our dependencies

**Comment by rishabh4uh** [comment]
0.16.1.0

**Comment by rishabh4uh** [comment]
@joeyballentine 0.16.1.0

**Comment by rishabh4uh** [comment]
Thanks though :)

**Comment by joeyballentine** [comment]
For context, there was some issue with that dependency that's erroring (though I don't remember that specific error) where it was being updated to a later verison that was causing problems. We fixed that issue pretty quickly, but you  obviously don't get that fix on old versions

**Comment by rishabh4uh** [comment]
yup, probably in 2-3 versions I guess but all good. Thanks for the info man

**Comment by joeyballentine** [comment]
This makes no sense. Unless you're using a super old version of chaiNNer, it should be installing a version of sanic that fixed this issue.

**Comment by vxish** [comment]
alright let me try that now

**Comment by joeyballentine** [comment]
Get rid of numpy from that. And get rid of pywin

**Comment by vxish** [comment]
> Get rid of numpy from that. And get rid of pywin

this is what I got in powershell:
```
PS C:\Users\User> pip install --upgrade sanic==21.9.3 Sanic-Cors==1.0.1 opencv-python==4.6.0.66 Pillow==9.2.0 appdirs==1.4.4 ffmpeg-python==0.2.0 --disable-pip-version-check
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/sanic/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/sanic/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/sanic/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/sanic/
Collecting sanic==21.9.3
  Using cached sanic-21.9.3-py3-none-any.whl (120 kB)
Collecting Sanic-Cors==1.0.1
  Using cached Sanic_Cors-1.0.1-py2.py3-none-any.whl (17 kB)
Collecting opencv-python==4.6.0.66
  Using cached opencv_python-4.6.0.66-cp36-abi3-win_amd64.whl (35.6 MB)
Collecting Pillow==9.2.0
  Downloading Pillow-9.2.0.tar.gz (50.0 MB)
     ---------------------------------------- 50.0/50.0 MB 5.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting appdirs==1.4.4
  Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting ffmpeg-python==0.2.0
  Downloading ffmpeg_python-0.2.0-py3-none-any.whl (25 kB)
Collecting sanic-routing~=0.7 (from sanic==21.9.3)
  Downloading sanic_routing-0.7.2-py3-none-any.whl (23 kB)
Requirement already satisfied: httptools>=0.0.10 in c:\users\User\appdata\local\programs\python\python312\lib\site-packages (from sanic==21.9.3) (0.6.1)
Requirement already satisfied: aiofiles>=0.6.0 in c:\users\User\appdata\local\programs\python\python312\lib\site-packages (from sanic==21.9.3) (23.2.1)
Requirement already satisfied: websockets>=10.0 in c:\users\User\appdata\local\programs\python\python312\lib\site-packages (from sanic==21.9.3) (11.0)
Collecting multidict<6.0,>=5.0 (from sanic==21.9.3)
  Downloading multidict-5.2.0.tar.gz (49 kB)
     ---------------------------------------- 49.0/49.0 kB 2.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting sanic-plugin-toolkit<2,>=1.2.0 (from Sanic-Cors==1.0.1)
  Downloading sanic_plugin_toolkit-1.2.1-py3-none-any.whl (33 kB)
Collecting numpy>=1.21.2 (from opencv-python==4.6.0.66)
  Downloading numpy-1.26.2-cp312-cp312-win_amd64.whl.metadata (61 kB)
     ---------------------------------------- 61.2/61.2 kB 1.6 MB/s eta 0:00:00
Collecting future (from ffmpeg-python==0.2.0)
  Downloading future-0.18.3.tar.gz (840 kB)
     ---------------------------------------- 840.9/840.9 kB 3.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: setuptools>=40.8 in c:\users\User\appdata\local\programs\python\python312\lib\site-packages (from sanic-plugin-toolkit<2,>=1.2.0->Sanic-Cors==1.0.1) (69.0.2)
Downloading numpy-1.26.2-cp312-cp312-win_amd64.whl (15.5 MB)
   ---------------------------------------- 15.5/15.5 MB 4.2 MB/s eta 0:00:00
Building wheels for collected packages: Pillow, multidict, future
  Building wheel for Pillow (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for Pillow (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [202 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-312
      creating build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\BdfFontFile.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\BlpImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\BmpImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\BufrStubImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ContainerIO.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\CurImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\DcxImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\DdsImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\EpsImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ExifTags.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\features.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\FitsImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\FitsStubImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\FliImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\FontFile.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\FpxImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\FtexImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\GbrImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\GdImageFile.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\GifImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\GimpGradientFile.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\GimpPaletteFile.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\GribStubImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\Hdf5StubImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\IcnsImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\IcoImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\Image.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageChops.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageCms.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageColor.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageDraw.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageDraw2.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageEnhance.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageFile.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageFilter.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageFont.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageGrab.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageMath.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageMode.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageMorph.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageOps.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImagePalette.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImagePath.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageQt.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageSequence.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageShow.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageStat.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageTk.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageTransform.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImageWin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\ImtImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\IptcImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\Jpeg2KImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\JpegImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\JpegPresets.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\McIdasImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\MicImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\MpegImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\MpoImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\MspImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\PaletteFile.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\PalmImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\PcdImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\PcfFontFile.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\PcxImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\PdfImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\PdfParser.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\PixarImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\PngImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\PpmImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\PsdImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\PSDraw.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\PyAccess.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\SgiImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\SpiderImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\SunImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\TarIO.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\TgaImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\TiffImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\TiffTags.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\WalImageFile.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\WebPImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\WmfImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\XbmImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\XpmImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\XVThumbImagePlugin.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\_binary.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\_deprecate.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\_tkinter_finder.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\_util.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\_version.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\__init__.py -> build\lib.win-amd64-cpython-312\PIL
      copying src\PIL\__main__.py -> build\lib.win-amd64-cpython-312\PIL
      running egg_info
      writing src\Pillow.egg-info\PKG-INFO
      writing dependency_links to src\Pillow.egg-info\dependency_links.txt
      writing requirements to src\Pillow.egg-info\requires.txt
      writing top-level names to src\Pillow.egg-info\top_level.txt
      reading manifest file 'src\Pillow.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.c'
      warning: no files found matching '*.h'
      warning: no files found matching '*.sh'
      warning: no files found matching '*.txt'
      warning: no previously-included files found matching '.appveyor.yml'
      warning: no previously-included files found matching '.clang-format'
      warning: no previously-included files found matching '.coveragerc'
      warning: no previously-included files found matching '.editorconfig'
      warning: no previously-included files found matching '.readthedocs.yml'
      warning: no previously-included files found matching 'codecov.yml'
      warning: no previously-included files matching '.git*' found anywhere in distribution
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      no previously-included directories found matching '.ci'
      adding license file 'LICENSE'
      writing manifest file 'src\Pillow.egg-info\SOURCES.txt'
      running build_ext


      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.

      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html

      Traceback (most recent call last):
        File "<string>", line 995, in <module>
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-n6ie5_40\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-n6ie5_40\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-n6ie5_40\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-n6ie5_40\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-n6ie5_40\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-n6ie5_40\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-n6ie5_40\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-n6ie5_40\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-n6ie5_40\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-n6ie5_40\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-n6ie5_40\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-n6ie5_40\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-n6ie5_40\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-n6ie5_40\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-n6ie5_40\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 88, in run
          _build_ext.run(self)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-n6ie5_40\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "<string>", line 810, in build_extensions
      RequiredDependencyException: zlib

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-n6ie5_40\overlay\Lib\site-packages\setuptools\build_meta.py", line 404, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-n6ie5_40\overlay\Lib\site-packages\setuptools\build_meta.py", line 389, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-n6ie5_40\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-n6ie5_40\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 1015, in <module>
      RequiredDependencyException:

      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.

      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html


      <string>:45: RuntimeWarning: Pillow 9.2.0 does not support Python 3.12 and does not provide prebuilt Windows binaries. We do not recommend building from source on Windows.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Pillow
  Building wheel for multidict (pyproject.toml) ... done
  Created wheel for multidict: filename=multidict-5.2.0-cp312-cp312-win_amd64.whl size=45217 sha256=f6e876a8202969a3e6893c99e1889787109dd9c0e1d92155619544395bafa2a5
  Stored in directory: c:\users\User\appdata\local\pip\cache\wheels\07\0a\62\442e1bcb8b0f747d3a636f3ce6d73e0e5d5784cf14edc38549
  Building wheel for future (pyproject.toml) ... done
  Created wheel for future: filename=future-0.18.3-py3-none-any.whl size=492054 sha256=7c48255c308fac66548fc34b0e6933a939541e5951f57f2ce4ccc1bf90ebb8c4
  Stored in directory: c:\users\User\appdata\local\pip\cache\wheels\f1\54\27\4e5cb4bd05116c097877e85a206a2e08d301aaa9b7af719909
Successfully built multidict future
Failed to build Pillow
ERROR: Could not build wheels for Pillow, which is required to install pyproject.toml-based projects
PS C:\Users\User>
```

**Comment by joeyballentine** [comment]
Ok, don't install to your system python, try installing to chainners python. Your python is some version these wheels aren't built for (3.12? Or maybe 3.7?)

**Comment by vxish** [comment]
> Ok, don't install to your system python, try installing to chainners python. Your python is some version these wheels aren't built for (3.12? Or maybe 3.7?)

yeah I am using Python 3.12.0

how can I make it install to the chainners python ?

**Comment by vxish** [comment]
and joey also what python version are the wheels built for?

**Comment by vxish** [comment]
Chainner python? 

```
PS C:\Users\User> cd C:\Users\User\AppData\Roaming\chaiNNer\python\python
PS C:\Users\User\AppData\Roaming\chaiNNer\python\python> ls


    Directory: C:\Users\User\AppData\Roaming\chaiNNer\python\python


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        30/11/2023  03:31 PM                DLLs
d-----        30/11/2023  03:31 PM                include
d-----        30/11/2023  03:31 PM                Lib
d-----        30/11/2023  03:31 PM                libs
d-----        30/11/2023  03:32 PM                Scripts
d-----        30/11/2023  03:31 PM                tcl
-a----        30/11/2023  03:31 PM          24921 LICENSE.txt
-a----        30/11/2023  03:31 PM          94208 python.exe
-a----        30/11/2023  03:31 PM         438272 python.pdb
-a----        30/11/2023  03:31 PM          52224 python3.dll
-a----        30/11/2023  03:31 PM         159744 python3.pdb
-a----        30/11/2023  03:31 PM        4488192 python39.dll
-a----        30/11/2023  03:31 PM       13692928 python39.pdb
-a----        30/11/2023  03:31 PM          92672 pythonw.exe
-a----        30/11/2023  03:31 PM         438272 pythonw.pdb
-a----        30/11/2023  03:31 PM          97168 vcruntime140.dll
-a----        30/11/2023  03:31 PM          37240 vcruntime140_1.dll


PS C:\Users\User\AppData\Roaming\chaiNNer\python\python> python --version
Python 3.12.0
PS C:\Users\User\AppData\Roaming\chaiNNer\python\python>
```

**Comment by joeyballentine** [comment]
Chainners python should be 3.11

**Comment by vxish** [comment]
> pip install --upgrade sanic==21.9.3 Sanic-Cors==1.0.1 opencv-python==4.6.0.66 Pillow==9.2.0 appdirs==1.4.4 ffmpeg-python==0.2.0 --disable-pip-version-check

I think chainner is running the following by default:

```
C:\Users\User\AppData\Roaming\chaiNNer\python\python>python --version
Python 3.9.7
```

**Comment by vxish** [comment]
Still no luck man, this program is nice but giving up trying to install it due to this issue.. @joeyballentine

**Comment by joeyballentine** [comment]
> @joeyballentine I think chainner is running the following by default:
> 
> ```
> C:\Users\User\AppData\Roaming\chaiNNer\python\python>python --version
> Python 3.9.7
> ```

It used to use 3.9. We updated it to 3.11 in one of the last major version updates

**Comment by RunDevelopment** [comment]
Closing this now, since the issue seems to have been resolved.
