### ISSUE TITLE
Cannot install PyTorch 1.12.1 as dependency since it has been updated to 2.0

### ISSUE THREAD

**Issue by wzxu** [chaiNNer-org/chaiNNer#1891]
**Information:**

- Chainner version: v0.18.9
- OS: macOS Ventura 13.4

**Description**
Tried using a SwinIR upscaling model today and found the CPU processing time and RAM usage intolerable. After some Googling I found that "mps" support was only added in PyTorch 1.12, and [judging from this](https://github.com/chaiNNer-org/chaiNNer/blob/main/backend/src/packages/chaiNNer_pytorch/__init__.py) I can't get it with the bundled Python, so I installed Python 3.11 via Homebrew and pointed Chainner to it. Surely enough, after restart Chainner was able to find it and list PyTorch 1.12.1 as dependency.

However, when I clicked "Install", the spinner started but the progress bar won't even show. After some minutes of inactivity, I restart Chainner and turned on "Use Pip Directly" to retry, and here's the message:
```
ERROR: Could not find a version that satisfies the requirement torch==1.12.1 (from versions: 2.0.0, 2.0.1)
ERROR: No matching distribution found for torch==1.12.1
Error: Pip process exited with non-zero exit code 1
```

Visiting the official PyTorch site I can also see the current download defaults to 2.0.1. 
Time to update the dependency?

**Comment by wzxu** [comment]
Oh… judging from https://download.pytorch.org/whl/torch/, looks I should've installed 3.10 instead? 
Will try and update back.

**Comment by wzxu** [comment]
My bad. Python 3.10 works, but mps raises exception in the program. 
```
RuntimeError: don't know how to restore data location of torch.storage._UntypedStorage (tagged with mps)
```
Some Googling tells me I might need to update to PyTorch 1.13 instead of 1.12. 
Will give it a try and probably open a new issue if needed. This one can be closed.

**Comment by wzxu** [comment]
Resolution: Use Python 3.10.

**Comment by wzxu** [comment]
> My bad. Python 3.10 installs just fine, but then I found out mps raises exception in the program.
> 
> ```
> RuntimeError: don't know how to restore data location of torch.storage._UntypedStorage (tagged with mps)
> ```
> 
> Some Googling tells me I might need to update to PyTorch 1.13 instead of 1.12. Will give it a try and probably open a new issue if needed. This one can be closed.

Successfully eliminated the error with PyTorch 1.13.1 + Torchvision 0.14.1.
Unfortunately it's missing some operations (albeit listed as implemented at https://github.com/pytorch/pytorch/issues/77764)
Will probably need to see if it's possible to build with PyTorch 2.0…

**Comment by wzxu** [comment]
2.0 builds. Unfortunately the one I need (roll) is still not in 2.0.1 as of right now according to https://qqaatw.dev/pytorch-mps-ops-coverage/ 😵

**Comment by joeyballentine** [comment]
If 2.1 is needed, we're planning on updating chaiNNer to use 3.11 and 2.1 when 2.1 releases. The only issue is we'll need to replace the current clipboard dependency which we already have a plan for.

Thanks for keeping this ticket updated with your experience using MPS and glad to know it actually works somewhat. Nobody else has ever ended up letting me know if they got it working

**Comment by wzxu** [comment]
> If 2.1 is needed, we're planning on updating chaiNNer to use 3.11 and 2.1 when 2.1 releases. The only issue is we'll need to replace the current clipboard dependency which we already have a plan for.
> 
> Thanks for keeping this ticket updated with your experience using MPS and glad to know it actually works somewhat. Nobody else has ever ended up letting me know if they got it working

Thanks for checking in! So I got it to build and installed PyTorch 2.0.1 and Torchvision 0.15.2 as dependencies. (Not sure if anything else breaks. Still just focusing on getting upscaling to work.)

As I mentioned above, many operation still aren't fully implemented in mps, and there seem to be an environment variable to fall back to CPU for individual operation instead of the device as a whole, if I'm understanding it correctly.
<img width="447" alt="image" src="https://github.com/chaiNNer-org/chaiNNer/assets/5619348/e908a214-0e40-4897-b018-a3349aea9461">

Can you give me a hint in which file I can set this variable so I can see if it really works?

**Comment by wzxu** [comment]
By the way, when I do npm install (using Node LTS 18.15.0) I got the following:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: use-http@1.0.26
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   react@"^18.1.0" from the root project
npm ERR!   peer react@">=18" from @chakra-ui/accordion@2.1.1
npm ERR!   node_modules/@chakra-ui/accordion
npm ERR!     @chakra-ui/accordion@"2.1.1" from @chakra-ui/react@2.3.5
npm ERR!     node_modules/@chakra-ui/react
npm ERR!       @chakra-ui/react@"^2.3.5" from the root project
npm ERR!   100 more (@chakra-ui/alert, @chakra-ui/avatar, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.13.1 || ^17.0.0" from use-http@1.0.26
npm ERR! node_modules/use-http
npm ERR!   use-http@"^1.0.26" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"^16.13.1 || ^17.0.0" from use-http@1.0.26
npm ERR!   node_modules/use-http
npm ERR!     use-http@"^1.0.26" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

I used pnpm install which seemed to builds and then run make successfully, but I just tried Upscale Face to see if other operations can hopefully work with mps, but was met with this error:
```
[2023-06-26 00:36:45.390] [error] Listener for event execution-error and data {"message":"Error running nodes!","source":{"nodeId":"9160245c-257f-4e1c-a2cb-d95a9812a0fd","schemaId":"chainner:pytorch:upscale_face","inputs":{}},"exception":"'NoneType' object has no attribute 'shape'"} errored:  TypeError: Cannot read properties of undefined (reading 'type')
    at file:///Applications/chaiNNer.app/Contents/Resources/app/.webpack/renderer/main_window/index.js:2:1037940
    at Array.map (<anonymous>)
    at xT (file:///Applications/chaiNNer.app/Contents/Resources/app/.webpack/renderer/main_window/index.js:2:1037883)
    at file:///Applications/chaiNNer.app/Contents/Resources/app/.webpack/renderer/main_window/index.js:2:1111502
    at EventSource.<anonymous> (file:///Applications/chaiNNer.app/Contents/Resources/app/.webpack/renderer/main_window/index.js:2:1045072)
```
So I think there might be something wrong with my build still and I didn't actually work around the issue by using pnpm. Could you also tell me how to solve the Node dependencies issue correctly?

**Comment by joeyballentine** [comment]
> Can you give me a hint in which file I can set this variable so I can see if it really works?

Should be this line: https://github.com/chaiNNer-org/chaiNNer/blob/6fd553e20e4b8d36598a58d8f0c1f371dd5ae333/src/main/backend/process.ts#L66

This is where we spawn the backend process and define its environment variables. Should be able to just add it to it's object.

> By the way, when I do npm install (using Node LTS 18.15.0) I got the following:

You should be able to resolve that by using either (or both) --legacy-peer-deps and --force, but I'm not entirely sure. I keep meaning to look into that since new contributors keep running into that issue

**Comment by wzxu** [comment]
> Should be this line:
> 
> https://github.com/chaiNNer-org/chaiNNer/blob/6fd553e20e4b8d36598a58d8f0c1f371dd5ae333/src/main/backend/process.ts#L66
> 
> This is where we spawn the backend process and define its environment variables. Should be able to just add it to it's object.

Good news! So I added `PYTORCH_ENABLE_MPS_FALLBACK: '1'` and it certainly worked.

SwinIR upscaling that used to take 2m7s now finishes in just 37s. Lovely to see all these cores being used.
<img width="392" alt="image" src="https://github.com/chaiNNer-org/chaiNNer/assets/5619348/53ab532e-4367-4083-b54d-93dd4dd87ae3">
RAM-wise, it used to oscillate and peak at 12GB, and now it's steady at just 5.3GB (however, before, the RAM would get released after processing finished, now the RAM usage grows slightly to 6.8GB and sticks around until I quit Chainner).

> You should be able to resolve that by using either (or both) --legacy-peer-deps and --force, but I'm not entirely sure. I keep meaning to look into that since new contributors keep running into that issue

Will just wait for you to resolve the dependency conflict since pnpm works for me now. However as my update mentioned, the problem seems to be related to using external Python and not the app itself. I get the same error (where Face Upscaling node doesn't get any input??) using the release build as well.

**Comment by joeyballentine** [comment]
> however, before, the RAM would get released after processing finished, now the RAM usage grows slightly to 6.8GB and sticks around until I quit Chainner

I bet this probably is just a pytorch thing from using the CPU fallback ops. Not sure what we'd be able to do about that.

> the problem seems to be related to using external Python and not the app itself.

That's a completely different issue from the dependency conflict stuff. As for that, my guess is facexlib isn't detecting a face there. Could you try a different image? If you get the same thing, it might be a pytorch 2 incompatibility or something

**Comment by wzxu** [comment]
> That's a completely different issue from the dependency conflict stuff. As for that, my guess is facexlib isn't detecting a face there. Could you try a different image? If you get the same thing, it might be a pytorch 2 incompatibility or something

@joeyballentine FYI I tried using PyTorch 1.13.1 + Torchvision 0.14.1 with integrated Python 3.9.11 and got the same error.

**Comment by joeyballentine** [comment]
Can you paste the actual error message you get please?

**Comment by RunDevelopment** [comment]
> I switched back to external Python but the error is the same as the one I posted above. Here it is again:
> 
> ```
> [2023-07-03 23:51:23.821] [info]  Python executable: /opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/bin/python3.10
> [2023-07-03 23:51:23.822] [info]  Running pip command: pip list --format=json --disable-pip-version-check
> [2023-07-03 23:53:17.500] [error] Listener for event execution-error and data {"message":"Error running nodes!","source":{"nodeId":"cb6d63c1-e4dc-4760-987d-13dce2cf1647","schemaId":"chainner:pytorch:upscale_face","inputs":{}},"exception":"'NoneType' object has no attribute 'shape'"} errored:  TypeError: Cannot read properties of undefined (reading 'type')
>     at file:///Applications/chaiNNer.app/Contents/Resources/app/.webpack/renderer/main_window/index.js:2:1037940
>     at Array.map (<anonymous>)
>     at xT (file:///Applications/chaiNNer.app/Contents/Resources/app/.webpack/renderer/main_window/index.js:2:1037883)
>     at file:///Applications/chaiNNer.app/Contents/Resources/app/.webpack/renderer/main_window/index.js:2:1111502
>     at EventSource.<anonymous> (file:///Applications/chaiNNer.app/Contents/Resources/app/.webpack/renderer/main_window/index.js:2:1045072)
> ```

Looks like a bug in the frontend this time. I'll look into it.

**Comment by RunDevelopment** [comment]
Anyway, this issue simply formats an existing error message, so it still won't work even after I fixed the frontend bug. The actual error message is:
```
'NoneType' object has no attribute 'shape'
```
Pretty generic. We'll have to see some logs to figure out where the error occurred.

**Comment by joeyballentine** [comment]
I'm betting it's just not detecting any faces, in which case we should probably show a better error message if so

**Comment by RunDevelopment** [comment]
Right now, we literally don't show the error from Upscale Face at all. The error above is internal error reporting stuff that failed (see #1908).

**Comment by wzxu** [comment]
> I'm betting it's just not detecting any faces, in which case we should probably show a better error message if so

Hmm I'm not so sure. With external Python 3.10, the error shows with every picture. If I switch back to integrated Python 3.9 and intentionally feed it a picture with no face, it just outputs the original picture without processing or any error. 

I also cloned [GFPGAN](https://github.com/TencentARC/GFPGAN) (referenced in facexlib page) and run its example script with the Python 3.10 + PyTorch 1.13.1 + Torchvision 0.14.1 I used and it ran normally.

---

Compiled a new build from main, and here's the output:
```
Error

An error occurred in a Upscale Face node:

Failed to run Face Upscale.

Input values:
• Image: RGB Image 512x512
• Model: Value of type 'nodes.impl.pytorch.architecture.face.codeformer.CodeFormer'
• Upscaled Background: None
• Output Scale: 1x
• Weight: 0.1
```

**Comment by wzxu** [comment]
So there's nothing in renderer.log but when I check main.log, finally some useful info! Looks like it's really mps-related:
```
[2023-07-05 03:05:23.427] [info]  Backend: [83463] [INFO] Running new executor...
[2023-07-05 03:05:24.171] [info]  Backend: [83463] [ERROR] Face Upscale failed: slow_conv2d_forward_mps: input(device='cpu') and weight(device=mps:0')  must be on the same device
[2023-07-05 03:05:24.272] [info]  Backend: [83463] [ERROR] Failed to run Face Upscale.
Traceback (most recent call last):
  File "/Applications/chaiNNer.app/Contents/Resources/src/packages/chaiNNer_pytorch/pytorch/restoration/upscale_face.py", line 183, in face_upscale_node
    result = upscale(
  File "/opt/homebrew/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Applications/chaiNNer.app/Contents/Resources/src/packages/chaiNNer_pytorch/pytorch/restoration/upscale_face.py", line 56, in upscale
    face_helper.get_face_landmarks_5(only_center_face=False, eye_dist_threshold=5)
  File "/opt/homebrew/lib/python3.10/site-packages/facexlib/utils/face_restoration_helper.py", line 139, in get_face_landmarks_5
    bboxes = self.face_det.detect_faces(input_img, 0.97) * scale
  File "/opt/homebrew/lib/python3.10/site-packages/facexlib/detection/retinaface.py", line 205, in detect_faces
    loc, conf, landmarks, priors = self.__detect_faces(image)
  File "/opt/homebrew/lib/python3.10/site-packages/facexlib/detection/retinaface.py", line 156, in __detect_faces
    loc, conf, landmarks = self(inputs)
  File "/opt/homebrew/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/facexlib/detection/retinaface.py", line 121, in forward
    out = self.body(inputs)
  File "/opt/homebrew/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/torchvision/models/_utils.py", line 69, in forward
    x = module(x)
  File "/opt/homebrew/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/opt/homebrew/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: slow_conv2d_forward_mps: input(device='cpu') and weight(device=mps:0')  must be on the same device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/chaiNNer.app/Contents/Resources/src/process.py", line 64, in run_node
    raw_output = node.run(*enforced_inputs)
  File "/Applications/chaiNNer.app/Contents/Resources/src/packages/chaiNNer_pytorch/pytorch/restoration/upscale_face.py", line 199, in face_upscale_node
    raise RuntimeError("Failed to run Face Upscale.")
RuntimeError: Failed to run Face Upscale.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Applications/chaiNNer.app/Contents/Resources/src/server.py", line 184, in run
    await executor.run()
  File "/Applications/chaiNNer.app/Contents/Resources/src/process.py", line 532, in run
    await self.__process_nodes(self.__get_output_nodes())
  File "/Applications/chaiNNer.app/Contents/Resources/src/process.py", line 519, in __process_nodes
    await self.process(output_node)
  File "/Applications/chaiNNer.app/Contents/Resources/src/process.py", line 346, in process
    return await self.__process(node)
  File "/Applications/chaiNNer.app/Contents/Resources/src/process.py", line 375, in __process
    processed_input = await self.process(node_input.id)
  File "/Applications/chaiNNer.app/Contents/Resources/src/process.py", line 346, in process
    return await self.__process(node)
  File "/Applications/chaiNNer.app/Contents/Resources/src/process.py", line 400, in __process
    output, execution_time = await self.loop.run_in_executor(
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Applications/chaiNNer.app/Contents/Resources/src/process.py", line 282, in wrapper
    result = supplier()
  File "/Applications/chaiNNer.app/Contents/Resources/src/process.py", line 83, in run_node
    raise NodeExecutionError(node_id, node, str(e), input_dict) from e
process.NodeExecutionError: Failed to run Face Upscale.
[2023-07-05 03:05:24.272] [info]  Backend: [83463] [ERROR] Traceback (most recent call last):
  File "/Applications/chaiNNer.app/Contents/Resources/src/packages/chaiNNer_pytorch/pytorch/restoration/upscale_face.py", line 183, in face_upscale_node
    result = upscale(
  File "/opt/homebrew/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Applications/chaiNNer.app/Contents/Resources/src/packages/chaiNNer_pytorch/pytorch/restoration/upscale_face.py", line 56, in upscale
    face_helper.get_face_landmarks_5(only_center_face=False, eye_dist_threshold=5)
  File "/opt/homebrew/lib/python3.10/site-packages/facexlib/utils/face_restoration_helper.py", line 139, in get_face_landmarks_5
    bboxes = self.face_det.detect_faces(input_img, 0.97) * scale
  File "/opt/homebrew/lib/python3.10/site-packages/facexlib/detection/retinaface.py", line 205, in detect_faces
    loc, conf, landmarks, priors = self.__detect_faces(image)
  File "/opt/homebrew/lib/python3.10/site-packages/facexlib/detection/retinaface.py", line 156, in __detect_faces
    loc, conf, landmarks = self(inputs)
  File "/opt/homebrew/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/facexlib/detection/retinaface.py", line 121, in forward
    out = self.body(inputs)
  File "/opt/homebrew/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/torchvision/models/_utils.py", line 69, in forward
    x = module(x)
  File "/opt/homebrew/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/opt/homebrew/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: slow_conv2d_forward_mps: input(device='cpu') and weight(device=mps:0')  must be on the same device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/chaiNNer.app/Contents/Resources/src/process.py", line 64, in run_node
    raw_output = node.run(*enforced_inputs)
  File "/Applications/chaiNNer.app/Contents/Resources/src/packages/chaiNNer_pytorch/pytorch/restoration/upscale_face.py", line 199, in face_upscale_node
    raise RuntimeError("Failed to run Face Upscale.")
RuntimeError: Failed to run Face Upscale.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Applications/chaiNNer.app/Contents/Resources/src/server.py", line 184, in run
    await executor.run()
  File "/Applications/chaiNNer.app/Contents/Resources/src/process.py", line 532, in run
    await self.__process_nodes(self.__get_output_nodes())
  File "/Applications/chaiNNer.app/Contents/Resources/src/process.py", line 519, in __process_nodes
    await self.process(output_node)
  File "/Applications/chaiNNer.app/Contents/Resources/src/process.py", line 346, in process
    return await self.__process(node)
  File "/Applications/chaiNNer.app/Contents/Resources/src/process.py", line 375, in __process
    processed_input = await self.process(node_input.id)
  File "/Applications/chaiNNer.app/Contents/Resources/src/process.py", line 346, in process
    return await self.__process(node)
  File "/Applications/chaiNNer.app/Contents/Resources/src/process.py", line 400, in __process
    output, execution_time = await self.loop.run_in_executor(
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Applications/chaiNNer.app/Contents/Resources/src/process.py", line 282, in wrapper
    result = supplier()
  File "/Applications/chaiNNer.app/Contents/Resources/src/process.py", line 83, in run_node
    raise NodeExecutionError(node_id, node, str(e), input_dict) from e
process.NodeExecutionError: Failed to run Face Upscale.
```

**Comment by wzxu** [comment]
Found a related discussion here: https://github.com/Mikubill/sd-webui-controlnet/discussions/860

**Comment by joeyballentine** [comment]
> Model: Value of type 'nodes.impl.pytorch.architecture.face.gfpganv1_clean_arch

We don't support GFPGAN V1. Try one of the later GFPGAN models instead

**Comment by joeyballentine** [comment]
Oh, I should have kept reading. The error does look MPS related I guess. It's coming directly from facexlib, so it's not a problem with chaiNNer specifically but the facexlib dependency. If using the latest version of facexlib doesn't work, then you'll have to open an issue there.

**Comment by wzxu** [comment]
> The error does look MPS related I guess. It's coming directly from facexlib, so it's not a problem with chaiNNer specifically but the facexlib dependency. If using the latest version of facexlib doesn't work, then you'll have to open an issue there.

Yup I manually changed a file in facexlib and can get past this error. Someone already opened an issue there to request specifying "device" in parameter (currently it only uses cuda and then cpu if not available). For reference: https://github.com/xinntao/facexlib/issues/18
