### ISSUE TITLE
Critical error when un-/installing dependencies

### ISSUE THREAD

**Issue by stonerl** [chaiNNer-org/chaiNNer#2038]
**Information:**

- Chainner version: [0.19.0]
- OS: [macOS 13.5]

**Description**
When installing or uninstalling dependencies, a critical error appears and disappears after a short while. Workaround in #2030

![CleanShot 2023-08-02 at 15 00 04](https://github.com/chaiNNer-org/chaiNNer/assets/2091312/642bfac6-1bdd-4a76-a4b2-274fbc97297a)

**Logs**
[localhost-1690992276719.log](https://github.com/chaiNNer-org/chaiNNer/files/12242258/localhost-1690992276719.log)

**Comment by RunDevelopment** [comment]
Here's the log cut down to the important bits:

```
18:03:54.801 › Beginning pip install...
18:03:55.344 › Found whl: ncnn_vulkan-2023.6.18-cp39-cp39-macosx_11_0_arm64.whl
18:03:59.378 › Attempting to kill backend...
Backend.ts:146     GET http://127.0.0.1:8000/nodes net::ERR_CONNECTION_REFUSED
fetchJson @ Backend.ts:146
nodes @ Backend.ts:154
queryFn @ BackendContext.tsx:98
18:03:59.378 › Successfully killed backend.
18:03:59.378 › Attempting to spawn backend...
18:03:59.379 › Backend: [87121] [INFO] Stopping worker [87121]
18:03:59.395 › TypeError: Failed to fetch
    at Backend.fetchJson (Backend.ts:146:62)
    at Backend.nodes (Backend.ts:154:21)
    at Object.queryFn (BackendContext.tsx:98:48)
Backend.ts:146     GET http://127.0.0.1:8000/dependencies net::ERR_CONNECTION_REFUSED
fetchJson @ Backend.ts:146
dependencies @ Backend.ts:220
queryFn @ DependencyContext.tsx:297
18:03:59.456 › TypeError: Failed to fetch
    at Backend.fetchJson (Backend.ts:146:62)
    at Backend.dependencies (Backend.ts:220:21)
    at Object.queryFn (DependencyContext.tsx:297:48)
18:03:59.768 › Backend: [87563] [INFO] Sanic v23.3.0
[2023-08-02 18:03:59 +0200] [87563] [INFO] Goin' Fast @ http://127.0.0.1:8000
18:03:59.768 › Backend: [87563] [INFO] mode: production, single worker
[2023-08-02 18:03:59 +0200] [87563] [INFO] server: sanic, HTTP/1.1
[2023-08-02 18:03:59 +0200] [87563] [INFO] python: 3.9.11
[2023-08-02 18:03:59 +0200] [87563] [INFO] platform: macOS-13.5-arm64-arm-64bit
[2023-08-02 18:03:59 +0200] [87563] [INFO] packages: sanic-routing==22.8.0
18:03:59.784 › Backend: [87563] [INFO] Starting setup...
18:03:59.784 › Backend: [87563] [INFO] Starting worker [87563]
18:04:01.984 › Backend: [87563] [INFO] Importing nodes...
18:04:01.985 › Backend: [87563] [INFO] Checking dependencies...
[2023-08-02 18:04:01 +0200] [87563] [INFO] Checking dependencies for chaiNNer_standard...
[2023-08-02 18:04:01 +0200] [87563] [INFO] Checking dependencies for PyTorch...
[2023-08-02 18:04:01 +0200] [87563] [INFO] Checking dependencies for NCNN...
[2023-08-02 18:04:01 +0200] [87563] [INFO] Checking dependencies for ONNX...
[2023-08-02 18:04:01 +0200] [87563] [INFO] Checking dependencies for External...
18:04:01.986 › Backend: [87563] [INFO] Done checking dependencies...
18:04:03.879 › Backend: [87563] [INFO] Sending backend ready...
18:04:06.078 › Backend: [87563] [INFO] Done.
18:04:14.697 › Backend: [87121] [INFO] Request: GET http://127.0.0.1:8000/sse stopped. Transport is closed.
[2023-08-02 18:04:14 +0200] [87121] [INFO] Request: GET http://127.0.0.1:8000/setup-sse stopped. Transport is closed.
[2023-08-02 18:04:14 +0200] [87121] [INFO] Server Stopped
18:04:14.754 › Python subprocess exited with code 0 and signal null
18:04:15.703 › Successfully connected to setup SSE.
```

As we can see, the UI attempts to refresh nodes immediately after we start installing things. I don't know why it does that, but it's also not wrong in trying to refresh nodes.

So I think the fix for this would be to wait until the backend is no longer restarting before we issue the fetch.

**Comment by RunDevelopment** [comment]
Reopening since #2043 didn't fix it.

@stonerl Could you post the renderer log for after #2043?

**Comment by stonerl** [comment]
@RunDevelopment 

here is the log:

[localhost-1691166438867.log](https://github.com/chaiNNer-org/chaiNNer/files/12262659/localhost-1691166438867.log)

**Comment by RunDevelopment** [comment]
Dependency installation is now done entirely by the backend itself, so this shouldn't be an issue anymore.
