### ISSUE TITLE
Error report: Object has been destroyed

### ISSUE THREAD

**Issue by hopelesscase** [chaiNNer-org/chaiNNer#2046]
```
TypeError: Object has been destroyed

    at p.<anonymous> (/Applications/chaiNNer.app/Contents/Resources/app/.webpack/main/index.js:2:530912)
    at p.emit (node:events:513:28)
    at B (/Applications/chaiNNer.app/Contents/Resources/app/.webpack/main/index.js:2:618844)
    at x (/Applications/chaiNNer.app/Contents/Resources/app/.webpack/main/index.js:2:618927)
    at IncomingMessage.<anonymous> (/Applications/chaiNNer.app/Contents/Resources/app/.webpack/main/index.js:2:618603)
    at IncomingMessage.emit (node:events:513:28)
    at Readable.read (node:internal/streams/readable:539:10)
    at flow (node:internal/streams/readable:1023:34)
    at resume_ (node:internal/streams/readable:1004:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```
ChaiNNer: chaiNNer 0.19.0
OS: macOS 10.18

Just to note: It says my macOS is 10.18, but I'm actually running 13.5. I was trying to update my dependencies when it threw errors. 

Logs from today: 

<details>

```
[2023-08-03 01:58:56.585] [info]  Attempting to check for a port...
[2023-08-03 01:58:56.628] [info]  Port found: 8000
[2023-08-03 01:58:56.635] [info]  Attempting to check Python env...
[2023-08-03 01:58:56.992] [info]  Final Python binary: /Users/username/Library/Application Support/chaiNNer/python/python/bin/python3.9
[2023-08-03 01:58:56.994] [info]  {
  python: '/Users/username/Library/Application Support/chaiNNer/python/python/bin/python3.9',
  version: '3.9.11'
}
[2023-08-03 01:58:57.003] [info]  Attempting to check Ffmpeg env...
[2023-08-03 01:58:57.045] [info]  Final ffmpeg binary: /Users/username/Library/Application Support/chaiNNer/ffmpeg/ffmpeg
[2023-08-03 01:58:57.046] [info]  Final ffprobe binary: /Users/username/Library/Application Support/chaiNNer/ffmpeg/ffprobe
[2023-08-03 01:58:57.114] [info]  Attempting to check Python deps...
[2023-08-03 01:58:57.117] [info]  Python executable: /Users/username/Library/Application Support/chaiNNer/python/python/bin/python3.9
[2023-08-03 01:58:57.119] [info]  Running pip command: pip list --format=json --disable-pip-version-check
[2023-08-03 01:58:57.534] [info]  Attempting to spawn backend...
[2023-08-03 01:58:58.842] [error] Backend: /Users/username/Library/Application Support/chaiNNer/python/python/lib/python3.9/site-packages/torchvision/io/image.py:11: UserWarning: Failed to load image Python extension: dlopen(/Users/username/Library/Application Support/chaiNNer/python/python/lib/python3.9/site-packages/torchvision/image.so, 0x0006): Library not loaded: @rpath/libpng16.16.dylib
  Referenced from: <5F6B6919-410D-397C-98F2-12C5934F9DBE> /Users/username/Library/Application Support/chaiNNer/python/python/lib/python3.9/site-packages/torchvision/image.so
  Reason: tried: '/Users/malfet/miniforge3/envs/py_39_torch-1.10.2/lib/libpng16.16.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/malfet/miniforge3/envs/py_39_torch-1.10.2/lib/libpng16.16.dylib' (no such file), '/Users/malfet/miniforge3/envs/py_39_torch-1.10.2/lib/libpng16.16.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/malfet/miniforge3/envs/py_39_torch-1.10.2/lib/libpng16.16.dylib' (no such file), '/Users/malfet/miniforge3/envs/py_39_torch-1.10.2/lib/libpng16.16.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/malfet/miniforge3/envs/py_39_torch-1.10.2/lib/libpng16.16.dylib' (no such file), '/Users/malfet/miniforge3/envs/py_39_torch-1.10.2/lib/libpng16.16.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/malfet/miniforge3/envs/py_39_torch-1.10.2/lib/libpng16.16.dylib' (no such file), '/usr/local/lib/libpng16.16.dylib' (no such file), '/usr/lib/libpng16.16.dylib' (no such file, not in dyld cache)
  warn(f"Failed to load image Python extension: {e}")
[2023-08-03 01:58:59.223] [info]  Backend: [2738] [ERROR] Pasteboard is not available.
Clipboard functionality will be disabled.
[2023-08-03 01:59:02.559] [info]  Backend: [2738] [WARNING] Failed to load packages.chaiNNer_external.external_stable_diffusion.automatic1111.txt2img (/Applications/chaiNNer.app/Contents/Resources/src/packages/chaiNNer_external/external_stable_diffusion/automatic1111/txt2img.py): 
If you want to use external stable diffusion nodes, run the Automatic1111 web ui with the --api flag, like so:

./webui.sh --api

To manually set where ChaiNNer looks for the API, use the
STABLE_DIFFUSION_PROTOCOL, STABLE_DIFFUSION_HOST, and STABLE_DIFFUSION_PORT
environment variables.

[2023-08-03 01:59:02.560] [info]  Backend: [2738] [WARNING] Failed to load packages.chaiNNer_external.external_stable_diffusion.automatic1111.interrogate (/Applications/chaiNNer.app/Contents/Resources/src/packages/chaiNNer_external/external_stable_diffusion/automatic1111/interrogate.py): Cannot connect to stable diffusion API service.
[2023-08-03 01:59:02 -0400] [2738] [WARNING] Failed to load packages.chaiNNer_external.external_stable_diffusion.automatic1111.upscaling (/Applications/chaiNNer.app/Contents/Resources/src/packages/chaiNNer_external/external_stable_diffusion/automatic1111/upscaling.py): Cannot connect to stable diffusion API service.
[2023-08-03 01:59:02 -0400] [2738] [WARNING] Failed to load packages.chaiNNer_external.external_stable_diffusion.automatic1111.inpainting (/Applications/chaiNNer.app/Contents/Resources/src/packages/chaiNNer_external/external_stable_diffusion/automatic1111/inpainting.py): Cannot connect to stable diffusion API service.
[2023-08-03 01:59:02.561] [info]  Backend: [2738] [WARNING] Failed to load packages.chaiNNer_external.external_stable_diffusion.automatic1111.img2img (/Applications/chaiNNer.app/Contents/Resources/src/packages/chaiNNer_external/external_stable_diffusion/automatic1111/img2img.py): Cannot connect to stable diffusion API service.
[2023-08-03 01:59:02 -0400] [2738] [WARNING] Failed to load packages.chaiNNer_external.external_stable_diffusion.automatic1111.outpainting (/Applications/chaiNNer.app/Contents/Resources/src/packages/chaiNNer_external/external_stable_diffusion/automatic1111/outpainting.py): Cannot connect to stable diffusion API service.
[2023-08-03 01:59:02 -0400] [2738] [INFO] []
[2023-08-03 01:59:02.654] [info]  Backend: [2738] [INFO] Sanic v23.3.0
[2023-08-03 01:59:02 -0400] [2738] [INFO] Goin' Fast @ http://127.0.0.1:8000
[2023-08-03 01:59:02 -0400] [2738] [INFO] mode: production, single worker
[2023-08-03 01:59:02 -0400] [2738] [INFO] server: sanic, HTTP/1.1
[2023-08-03 01:59:02.655] [info]  Backend: [2738] [INFO] python: 3.9.11
[2023-08-03 01:59:02 -0400] [2738] [INFO] platform: macOS-13.5-arm64-i386-64bit
[2023-08-03 01:59:02 -0400] [2738] [INFO] packages: sanic-routing==22.8.0
[2023-08-03 01:59:02.671] [info]  Backend: [2738] [INFO] Starting worker [2738]
[2023-08-03 01:59:44.695] [info]  Attempting to kill backend...
[2023-08-03 01:59:44.708] [info]  Successfully killed backend.
[2023-08-03 01:59:44.722] [info]  Backend: [2738] [INFO] Stopping worker [2738]
[2023-08-03 01:59:44.724] [info]  Cleaning up temp folders...
[2023-08-03 02:00:43.658] [info]  Attempting to check for a port...
[2023-08-03 02:00:43.697] [info]  Port found: 8000
[2023-08-03 02:00:43.709] [info]  Attempting to check Python env...
[2023-08-03 02:00:44.130] [info]  Final Python binary: /Users/username/Library/Application Support/chaiNNer/python/python/bin/python3.9
[2023-08-03 02:00:44.131] [info]  {
  python: '/Users/username/Library/Application Support/chaiNNer/python/python/bin/python3.9',
  version: '3.9.11'
}
[2023-08-03 02:00:44.140] [info]  Attempting to check Ffmpeg env...
[2023-08-03 02:00:44.151] [info]  Final ffmpeg binary: /Users/username/Library/Application Support/chaiNNer/ffmpeg/ffmpeg
[2023-08-03 02:00:44.152] [info]  Final ffprobe binary: /Users/username/Library/Application Support/chaiNNer/ffmpeg/ffprobe
[2023-08-03 02:00:44.158] [info]  Attempting to spawn backend...
[2023-08-03 02:00:44.742] [info]  Backend: 
[2023-08-03 02:00:45.084] [info]  Backend: 
[2023-08-03 02:00:45.423] [info]  Backend: 
[2023-08-03 02:00:45.571] [info]  Backend: 
[2023-08-03 02:00:45.699] [info]  Backend: 
[2023-08-03 02:00:45.726] [info]  Backend: 
[2023-08-03 02:00:45.899] [info]  Backend: 
[2023-08-03 02:00:45.900] [info]  Backend: 
[2023-08-03 02:00:46.047] [info]  Backend: 
[2023-08-03 02:00:46.049] [info]  Backend: 
[2023-08-03 02:00:46.058] [info]  Backend: 
[2023-08-03 02:00:46.059] [info]  Backend: 
[2023-08-03 02:00:46.114] [info]  Backend: 
[2023-08-03 02:00:46.504] [info]  Backend: 
[2023-08-03 02:00:47.297] [info]  Backend: 
[2023-08-03 02:00:47.298] [info]  Backend: 
[2023-08-03 02:00:47.302] [info]  Backend: 
[2023-08-03 02:00:47.303] [info]  Backend: 
[2023-08-03 02:00:47.326] [error] Backend: ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sanic-plugin-toolkit 1.2.1 requires sanic<21.12.0,>=21.3.1, but you have sanic 23.3.0 which is incompatible.
[2023-08-03 02:00:47.328] [info]  Backend: 
[2023-08-03 02:00:47.972] [info]  Backend: [2846] [INFO] Sanic v23.3.0
[2023-08-03 02:00:47 -0400] [2846] [INFO] Goin' Fast @ http://127.0.0.1:8000
[2023-08-03 02:00:47 -0400] [2846] [INFO] mode: production, single worker
[2023-08-03 02:00:47 -0400] [2846] [INFO] server: sanic, HTTP/1.1
[2023-08-03 02:00:47 -0400] [2846] [INFO] python: 3.9.11
[2023-08-03 02:00:47 -0400] [2846] [INFO] platform: macOS-13.5-arm64-i386-64bit
[2023-08-03 02:00:47 -0400] [2846] [INFO] packages: sanic-routing==22.8.0
[2023-08-03 02:00:47.989] [info]  Backend: [2846] [INFO] Starting setup...
[2023-08-03 02:00:47.989] [info]  Backend: [2846] [INFO] Starting worker [2846]
[2023-08-03 02:00:48.289] [info]  Successfully connected to setup SSE.
[2023-08-03 02:00:48.309] [info]  Backend: [2846] [INFO] Importing nodes...
[2023-08-03 02:00:48.311] [info]  Backend: [2846] [INFO] Checking dependencies...
[2023-08-03 02:00:48 -0400] [2846] [INFO] Checking dependencies for chaiNNer_standard...
[2023-08-03 02:00:48 -0400] [2846] [INFO] Checking dependencies for PyTorch...
[2023-08-03 02:00:48.312] [info]  Backend: [2846] [INFO] Checking dependencies for NCNN...
[2023-08-03 02:00:48 -0400] [2846] [INFO] Checking dependencies for ONNX...
[2023-08-03 02:00:48 -0400] [2846] [INFO] Checking dependencies for External...
[2023-08-03 02:00:48.745] [info]  Backend: [2846] [INFO] Collecting wcmatch==8.4.1
[2023-08-03 02:00:48.960] [info]  Backend: [2846] [INFO] Downloading wcmatch-8.4.1-py3-none-any.whl (39 kB)
[2023-08-03 02:00:49.080] [info]  Backend: [2846] [INFO] Collecting chainner_ext==0.1.0
[2023-08-03 02:00:49.132] [info]  Backend: [2846] [INFO] Downloading chainner_ext-0.1.0-cp39-cp39-macosx_11_0_arm64.whl (772 kB)
[2023-08-03 02:00:49.143] [info]  Backend: [2846] [INFO] Progress: {"current": 10240, "total": 772356}
[2023-08-03 02:00:49.271] [info]  Backend: [2846] [INFO] Progress: {"current": 772356, "total": 772356}
[2023-08-03 02:00:49.334] [info]  Backend: [2846] [INFO] Collecting pasteboard==0.3.3
[2023-08-03 02:00:49.383] [info]  Backend: [2846] [INFO] Downloading pasteboard-0.3.3.tar.gz (13 kB)
[2023-08-03 02:00:49.403] [info]  Backend: [2846] [INFO] Installing build dependencies: started
[2023-08-03 02:00:51.667] [info]  Backend: [2846] [INFO] Installing build dependencies: finished with status 'done'
[2023-08-03 02:00:51.668] [info]  Backend: [2846] [INFO] Getting requirements to build wheel: started
[2023-08-03 02:00:51.718] [info]  Backend: [2846] [INFO] Getting requirements to build wheel: finished with status 'done'
[2023-08-03 02:00:51.719] [info]  Backend: [2846] [INFO] Preparing metadata (pyproject.toml): started
[2023-08-03 02:00:51.834] [info]  Backend: [2846] [INFO] Preparing metadata (pyproject.toml): finished with status 'done'
[2023-08-03 02:00:51.874] [info]  Backend: [2846] [INFO] Collecting bracex>=2.1.1 (from wcmatch==8.4.1)
[2023-08-03 02:00:51.896] [info]  Backend: [2846] [INFO] Downloading bracex-2.3.post1-py3-none-any.whl (12 kB)
[2023-08-03 02:00:51.907] [info]  Backend: [2846] [INFO] Requirement already satisfied: numpy>=1.16.0 in /Users/username/Library/Application Support/chaiNNer/python/python/lib/python3.9/site-packages (from chainner_ext==0.1.0) (1.23.2)
[2023-08-03 02:00:51.909] [info]  Backend: [2846] [INFO] Building wheels for collected packages: pasteboard
[2023-08-03 02:00:51.909] [info]  Backend: [2846] [INFO] Building wheel for pasteboard (pyproject.toml): started
[2023-08-03 02:01:23.626] [info]  Backend: [2846] [INFO] Building wheel for pasteboard (pyproject.toml): finished with status 'done'
[2023-08-03 02:01:23.633] [info]  Backend: [2846] [INFO] Created wheel for pasteboard: filename=pasteboard-0.3.3-cp39-cp39-macosx_13_0_arm64.whl size=13199 sha256=6d35b79627d804f447c6a063389f5a35d088d85447f302c2415abdee4a85e770
[2023-08-03 02:01:23 -0400] [2846] [INFO] Stored in directory: /Users/username/Library/Caches/chainner_pip/wheels/41/2f/20/bb834e1c541c36ab2078c1eb01fb37c451f8bbe1e562e420e0
[2023-08-03 02:01:23 -0400] [2846] [INFO] Successfully built pasteboard
[2023-08-03 02:01:23.745] [info]  Backend: [2846] [INFO] Installing collected packages: pasteboard, chainner_ext, bracex, wcmatch
[2023-08-03 02:01:23.803] [info]  Backend: [2846] [INFO] Successfully installed bracex-2.3.post1 chainner_ext-0.1.0 pasteboard-0.3.3 wcmatch-8.4.1
[2023-08-03 02:01:23.900] [info]  Backend: [2846] [INFO] Done checking dependencies...
[2023-08-03 02:01:24.286] [error] Backend: /Users/username/Library/Application Support/chaiNNer/python/python/lib/python3.9/site-packages/torchvision/io/image.py:11: UserWarning: Failed to load image Python extension: dlopen(/Users/username/Library/Application Support/chaiNNer/python/python/lib/python3.9/site-packages/torchvision/image.so, 0x0006): Library not loaded: @rpath/libpng16.16.dylib
  Referenced from: <5F6B6919-410D-397C-98F2-12C5934F9DBE> /Users/username/Library/Application Support/chaiNNer/python/python/lib/python3.9/site-packages/torchvision/image.so
  Reason: tried: '/Users/malfet/miniforge3/envs/py_39_torch-1.10.2/lib/libpng16.16.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/malfet/miniforge3/envs/py_39_torch-1.10.2/lib/libpng16.16.dylib' (no such file), '/Users/malfet/miniforge3/envs/py_39_torch-1.10.2/lib/libpng16.16.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/malfet/miniforge3/envs/py_39_torch-1.10.2/lib/libpng16.16.dylib' (no such file), '/Users/malfet/miniforge3/envs/py_39_torch-1.10.2/lib/libpng16.16.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/malfet/miniforge3/envs/py_39_torch-1.10.2/lib/libpng16.16.dylib' (no such file), '/Users/malfet/miniforge3/envs/py_39_torch-1.10.2/lib/libpng16.16.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/malfet/miniforge3/envs/py_39_torch-1.10.2/lib/libpng16.16.dylib' (no such file), '/usr/local/lib/libpng16.16.dylib' (no such file), '/usr/lib/libpng16.16.dylib' (no such file, not in dyld cache)
  warn(f"Failed to load image Python extension: {e}")
[2023-08-03 02:01:24.860] [info]  Backend: [2846] [ERROR] Pasteboard is not available.
Clipboard functionality will be disabled.
[2023-08-03 02:01:27.820] [info]  Backend: [2846] [WARNING] Failed to load packages.chaiNNer_external.external_stable_diffusion.automatic1111.outpaint (/Applications/chaiNNer.app/Contents/Resources/src/packages/chaiNNer_external/external_stable_diffusion/automatic1111/outpaint.py): 
If you want to use external stable diffusion nodes, run the Automatic1111 web ui with the --api flag, like so:

./webui.sh --api

To manually set where ChaiNNer looks for the API, use the
STABLE_DIFFUSION_PROTOCOL, STABLE_DIFFUSION_HOST, and STABLE_DIFFUSION_PORT
environment variables.

[2023-08-03 02:01:27.821] [info]  Backend: [2846] [WARNING] Failed to load packages.chaiNNer_external.external_stable_diffusion.automatic1111.inpaint (/Applications/chaiNNer.app/Contents/Resources/src/packages/chaiNNer_external/external_stable_diffusion/automatic1111/inpaint.py): Cannot connect to stable diffusion API service.
[2023-08-03 02:01:27.821] [info]  Backend: [2846] [WARNING] Failed to load packages.chaiNNer_external.external_stable_diffusion.automatic1111.text_to_image (/Applications/chaiNNer.app/Contents/Resources/src/packages/chaiNNer_external/external_stable_diffusion/automatic1111/text_to_image.py): Cannot connect to stable diffusion API service.
[2023-08-03 02:01:27.821] [info]  Backend: [2846] [WARNING] Failed to load packages.chaiNNer_external.external_stable_diffusion.automatic1111.clip_interrogate (/Applications/chaiNNer.app/Contents/Resources/src/packages/chaiNNer_external/external_stable_diffusion/automatic1111/clip_interrogate.py): Cannot connect to stable diffusion API service.
[2023-08-03 02:01:27.822] [info]  Backend: [2846] [WARNING] Failed to load packages.chaiNNer_external.external_stable_diffusion.automatic1111.upscale (/Applications/chaiNNer.app/Contents/Resources/src/packages/chaiNNer_external/external_stable_diffusion/automatic1111/upscale.py): Cannot connect to stable diffusion API service.
[2023-08-03 02:01:27.823] [info]  Backend: [2846] [WARNING] Failed to load packages.chaiNNer_external.external_stable_diffusion.automatic1111.image_to_image (/Applications/chaiNNer.app/Contents/Resources/src/packages/chaiNNer_external/external_stable_diffusion/automatic1111/image_to_image.py): Cannot connect to stable diffusion API service.
[2023-08-03 02:01:27.823] [info]  Backend: [2846] [INFO] [ModuleNotFoundError("No module named 'onnxoptimizer'"), ModuleNotFoundError("No module named 'onnxoptimizer'"), ModuleNotFoundError("No module named 'onnxoptimizer'"), ModuleNotFoundError("No module named 'onnxoptimizer'")]
[2023-08-03 02:01:27 -0400] [2846] [INFO] Sending backend ready...
[2023-08-03 02:01:27.925] [info]  Backend: [2846] [INFO] Done.
[2023-08-03 02:02:42.474] [info]  Attempting to kill backend...
[2023-08-03 02:02:42.474] [info]  Successfully killed backend.
[2023-08-03 02:02:42.474] [info]  Attempting to spawn backend...
[2023-08-03 02:02:42.479] [info]  Backend: [2846] [INFO] Stopping worker [2846]
[2023-08-03 02:02:42.890] [info]  Backend: [3070] [INFO] Sanic v23.3.0
[2023-08-03 02:02:42 -0400] [3070] [INFO] Goin' Fast @ http://127.0.0.1:8000
[2023-08-03 02:02:42 -0400] [3070] [INFO] mode: production, single worker
[2023-08-03 02:02:42 -0400] [3070] [INFO] server: sanic, HTTP/1.1
[2023-08-03 02:02:42 -0400] [3070] [INFO] python: 3.9.11
[2023-08-03 02:02:42 -0400] [3070] [INFO] platform: macOS-13.5-arm64-i386-64bit
[2023-08-03 02:02:42 -0400] [3070] [INFO] packages: sanic-routing==22.8.0
[2023-08-03 02:02:42.907] [info]  Backend: [3070] [INFO] Starting setup...
[2023-08-03 02:02:42.908] [info]  Backend: [3070] [INFO] Starting worker [3070]
[2023-08-03 02:02:45.116] [info]  Backend: [3070] [INFO] Importing nodes...
[2023-08-03 02:02:45.117] [info]  Backend: [3070] [INFO] Checking dependencies...
[2023-08-03 02:02:45 -0400] [3070] [INFO] Checking dependencies for chaiNNer_standard...
[2023-08-03 02:02:45.117] [info]  Backend: [3070] [INFO] Checking dependencies for PyTorch...
[2023-08-03 02:02:45 -0400] [3070] [INFO] Checking dependencies for NCNN...
[2023-08-03 02:02:45 -0400] [3070] [INFO] Checking dependencies for ONNX...
[2023-08-03 02:02:45 -0400] [3070] [INFO] Checking dependencies for External...
[2023-08-03 02:02:45 -0400] [3070] [INFO] Done checking dependencies...
[2023-08-03 02:02:48.764] [info]  Backend: [3070] [ERROR] Pasteboard is not available.
Clipboard functionality will be disabled.
[2023-08-03 02:02:49.092] [info]  Backend: [3070] [WARNING] Failed to load packages.chaiNNer_external.external_stable_diffusion.automatic1111.outpaint (/Applications/chaiNNer.app/Contents/Resources/src/packages/chaiNNer_external/external_stable_diffusion/automatic1111/outpaint.py): 
If you want to use external stable diffusion nodes, run the Automatic1111 web ui with the --api flag, like so:

./webui.sh --api

To manually set where ChaiNNer looks for the API, use the
STABLE_DIFFUSION_PROTOCOL, STABLE_DIFFUSION_HOST, and STABLE_DIFFUSION_PORT
environment variables.

[2023-08-03 02:02:49.093] [info]  Backend: [3070] [WARNING] Failed to load packages.chaiNNer_external.external_stable_diffusion.automatic1111.inpaint (/Applications/chaiNNer.app/Contents/Resources/src/packages/chaiNNer_external/external_stable_diffusion/automatic1111/inpaint.py): Cannot connect to stable diffusion API service.
[2023-08-03 02:02:49 -0400] [3070] [WARNING] Failed to load packages.chaiNNer_external.external_stable_diffusion.automatic1111.text_to_image (/Applications/chaiNNer.app/Contents/Resources/src/packages/chaiNNer_external/external_stable_diffusion/automatic1111/text_to_image.py): Cannot connect to stable diffusion API service.
[2023-08-03 02:02:49 -0400] [3070] [WARNING] Failed to load packages.chaiNNer_external.external_stable_diffusion.automatic1111.clip_interrogate (/Applications/chaiNNer.app/Contents/Resources/src/packages/chaiNNer_external/external_stable_diffusion/automatic1111/clip_interrogate.py): Cannot connect to stable diffusion API service.
[2023-08-03 02:02:49 -0400] [3070] [WARNING] Failed to load packages.chaiNNer_external.external_stable_diffusion.automatic1111.upscale (/Applications/chaiNNer.app/Contents/Resources/src/packages/chaiNNer_external/external_stable_diffusion/automatic1111/upscale.py): Cannot connect to stable diffusion API service.
[2023-08-03 02:02:49 -0400] [3070] [WARNING] Failed to load packages.chaiNNer_external.external_stable_diffusion.automatic1111.image_to_image (/Applications/chaiNNer.app/Contents/Resources/src/packages/chaiNNer_external/external_stable_diffusion/automatic1111/image_to_image.py): Cannot connect to stable diffusion API service.
[2023-08-03 02:02:49 -0400] [3070] [INFO] [ModuleNotFoundError("No module named 'onnxoptimizer'"), ModuleNotFoundError("No module named 'onnxoptimizer'"), ModuleNotFoundError("No module named 'onnxoptimizer'"), ModuleNotFoundError("No module named 'onnxoptimizer'")]
[2023-08-03 02:02:49.094] [info]  Backend: [3070] [INFO] Sending backend ready...
[2023-08-03 02:02:51.303] [info]  Backend: [3070] [INFO] Done.
[2023-08-03 02:02:57.811] [info]  Backend: [2846] [INFO] Request: GET http://127.0.0.1:8000/sse stopped. Transport is closed.
[2023-08-03 02:02:57.818] [info]  Backend: [2846] [INFO] Request: GET http://127.0.0.1:8000/setup-sse stopped. Transport is closed.
[2023-08-03 02:02:57.819] [info]  Backend: [2846] [INFO] Server Stopped
[2023-08-03 02:02:58.059] [error] Python subprocess exited with code 0 and signal null
[2023-08-03 02:02:58.818] [info]  Successfully connected to setup SSE.
[2023-08-03 02:03:23.707] [info]  Attempting to kill backend...
[2023-08-03 02:03:23.708] [info]  Successfully killed backend.
[2023-08-03 02:03:23.708] [info]  Attempting to spawn backend...
[2023-08-03 02:03:23.709] [info]  Backend: [3070] [INFO] Stopping worker [3070]
[2023-08-03 02:03:24.120] [info]  Backend: [3088] [INFO] Sanic v23.3.0
[2023-08-03 02:03:24 -0400] [3088] [INFO] Goin' Fast @ http://127.0.0.1:8000
[2023-08-03 02:03:24 -0400] [3088] [INFO] mode: production, single worker
[2023-08-03 02:03:24 -0400] [3088] [INFO] server: sanic, HTTP/1.1
[2023-08-03 02:03:24 -0400] [3088] [INFO] python: 3.9.11
[2023-08-03 02:03:24 -0400] [3088] [INFO] platform: macOS-13.5-arm64-i386-64bit
[2023-08-03 02:03:24 -0400] [3088] [INFO] packages: sanic-routing==22.8.0
[2023-08-03 02:03:24.136] [info]  Backend: [3088] [INFO] Starting setup...
[2023-08-03 02:03:24.137] [info]  Backend: [3088] [INFO] Starting worker [3088]
[2023-08-03 02:03:39.088] [info]  Backend: [3070] [INFO] Request: GET http://127.0.0.1:8000/setup-sse stopped. Transport is closed.
[2023-08-03 02:03:39 -0400] [3070] [INFO] Server Stopped
[2023-08-03 02:03:39.312] [error] Python subprocess exited with code 0 and signal null
[2023-08-03 02:03:40.105] [info]  Successfully connected to setup SSE.
[2023-08-03 02:03:53.992] [error] Unhandled Exception TypeError: Object has been destroyed
    at p.<anonymous> (/Applications/chaiNNer.app/Contents/Resources/app/.webpack/main/index.js:2:530912)
    at p.emit (node:events:513:28)
    at B (/Applications/chaiNNer.app/Contents/Resources/app/.webpack/main/index.js:2:618844)
    at x (/Applications/chaiNNer.app/Contents/Resources/app/.webpack/main/index.js:2:618927)
    at IncomingMessage.<anonymous> (/Applications/chaiNNer.app/Contents/Resources/app/.webpack/main/index.js:2:618603)
    at IncomingMessage.emit (node:events:513:28)
    at Readable.read (node:internal/streams/readable:539:10)
    at flow (node:internal/streams/readable:1023:34)
    at resume_ (node:internal/streams/readable:1004:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

</details>

**Comment by joeyballentine** [comment]
In all of these cases it's reporting that the MacOS version is 10.18. I gotta assume it's because of some compatibility mode that doesn't actually work right. Are you using an apple silicon device?

**Comment by hopelesscase** [comment]
Yup. M1.

**Comment by stonerl** [comment]
@hopelesscase Where did it report the OS version as 10.18?

For context, macOS 13 gets reported as 10.18 when a compatibility environment variable is set to true.

**Comment by stonerl** [comment]
@RunDevelopment Could this be the same as #1752? If so then it is fixed.

@hopelesscase Did this error occur after you closed the main window?

**Comment by RunDevelopment** [comment]
@hopelesscase As @stonerl pointed out, we think that this issue has been fixed already. Could you please test our latest release (v0.19.1) and see whether the issue has been fixed for you? You can [download it here](https://chainner.app/download).

**Comment by hopelesscase** [comment]
I do think it's been fixed… I haven't been able to replicate it since updating… I tried switching to my homebrew/system python and it works just fine. I didn't have it on the system python before this since it didn't work early on in chiNNer's history, but it's working so smoothly now. Not sure which setting is better, but I'll leave as is for now and learn more.

Sorry I can't seem to replicate it, but also it's wonderful that I can't. Thank you very much for helping me!
