### ISSUE TITLE
chaiNNer portable on macOS not working

### ISSUE THREAD

**Issue by stonerl** [chaiNNer-org/chaiNNer#2118]
**Information:**

- Chainner version: [0.19.3]
- OS: [macOS 13.5]

**Description**
The portable version for macOS does crash right at start. See the logs.

From what I can see is that the portable version also tries to create the folder `~/Library/Application Support/chaiNNer`. Which defeats the purpose of a portable version.

When I try to `ls` the folder `/private/var/folders/18/vsdmvwsd6rn8jb0gl5bxz3m00000gn/T/AppTranslocation/D6793BF4-8E26-4C6D-BB06-622E6E49A1D6`I get `ls: fts_read: Result too large`

To be honest, I really don't see a reason, for a portable version on macOS and I would vote for getting rid of it. @joeyballentine I guess you have insights on the number of downloads, but I assume not many people have ever downloaded it.

**Logs**
```
Uncaught Exception:
Error: ENOENT: no such file or directory, mkdir '/private/var/folders/18/vsdmvwsd6rn8jb0gl5bxz3m00000gn/T/AppTranslocation/D0082444-A382-4580-8580-A0D34A769B1C/d/chaiNNer.app/Contents/MacOS/settings'
at Object.mkdirSync (node:fs:1396:3)
at n._init (/private/var/folders/18/vsdmvwsd6rn8jb0gl5bxz3m00000gn/T/AppTranslocation/D0082444-A382-4580-8580-A0D34A769B1C/d/chaiNNer.app/Contents/Resources/app/.webpack/main/index.js:2:669251)
at new n (/private/var/folders/18/vsdmvwsd6rn8jb0gl5bxz3m00000gn/T/AppTranslocation/D0082444-A382-4580-8580-A0D34A769B1C/d/chaiNNer.app/Contents/Resources/app/.webpack/main/index.js:2:668304)
at 973 (/private/var/folders/18/vsdmvwsd6rn8jb0gl5bxz3m00000gn/T/AppTranslocation/D0082444-A382-4580-8580-A0D34A769B1C/d/chaiNNer.app/Contents/Resources/app/.webpack/main/index.js:2:514094)
at n (/private/var/folders/18/vsdmvwsd6rn8jb0gl5bxz3m00000gn/T/AppTranslocation/D0082444-A382-4580-8580-A0D34A769B1C/d/chaiNNer.app/Contents/Resources/app/.webpack/main/index.js:2:1841605)
at /private/var/folders/18/vsdmvwsd6rn8jb0gl5bxz3m00000gn/T/AppTranslocation/D0082444-A382-4580-8580-A0D34A769B1C/d/chaiNNer.app/Contents/Resources/app/.webpack/main/index.js:2:1842173
at Object.<anonymous> (/private/var/folders/18/vsdmvwsd6rn8jb0gl5bxz3m00000gn/T/AppTranslocation/D0082444-A382-4580-8580-A0D34A769B1C/d/chaiNNer.app/Contents/Resources/app/.webpack/main/index.js:2:1842202)
at Module._compile (node:internal/modules/cjs/loader:1269:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
at Module.load (node:internal/modules/cjs/loader:1124:32)
```

**Comment by joeyballentine** [comment]
Dang I'm surprised this wasn't reported sooner. Sure, we can just get rid of it if there's no point to it

**Comment by stonerl** [comment]
I guess nobody really used it … PR opened.
