### ISSUE TITLE
Text as Image node is broken for PIL 10

### ISSUE THREAD

**Issue by RunDevelopment** [chaiNNer-org/chaiNNer#2212]
@adegerard Do you happen to know why this happens?

![image](https://github.com/chaiNNer-org/chaiNNer/assets/20878432/d29d0afd-0da1-4477-90cb-9ec03a3de4e8)
![image](https://github.com/chaiNNer-org/chaiNNer/assets/20878432/54a2d9cb-9572-4cbf-b6dc-0370bcc7df9e)

Logs:

<details>

```
[2023-09-13 20:14:00 +0200] [6492] [INFO] Sanic v23.3.0
[2023-09-13 20:14:00 +0200] [6492] [INFO] Goin' Fast @ http://127.0.0.1:8000
[2023-09-13 20:14:00 +0200] [6492] [INFO] mode: production, single worker
[2023-09-13 20:14:00 +0200] [6492] [INFO] server: sanic, HTTP/1.1
[2023-09-13 20:14:00 +0200] [6492] [INFO] python: 3.8.2
[2023-09-13 20:14:00 +0200] [6492] [INFO] platform: Windows-10-10.0.19041-SP0
[2023-09-13 20:14:00 +0200] [6492] [INFO] packages: sanic-routing==22.8.0
[2023-09-13 20:14:00 +0200] [6492] [INFO] Starting setup...
[2023-09-13 20:14:00 +0200] [6492] [INFO] Starting worker [6492]
[2023-09-13 20:14:00 +0200] [6492] [INFO] Importing nodes...
[2023-09-13 20:14:00 +0200] [6492] [INFO] Checking dependencies...
[2023-09-13 20:14:00 +0200] [6492] [INFO] Checking dependencies for chaiNNer_standard...
[2023-09-13 20:14:00 +0200] [6492] [INFO] Checking dependencies for PyTorch...
[2023-09-13 20:14:00 +0200] [6492] [INFO] Checking dependencies for NCNN...
[2023-09-13 20:14:00 +0200] [6492] [INFO] Checking dependencies for ONNX...
[2023-09-13 20:14:00 +0200] [6492] [INFO] Checking dependencies for External...
[2023-09-13 20:14:00 +0200] [6492] [INFO] Done checking dependencies...
[2023-09-13 20:14:02 +0200] [6492] [INFO] Sending backend ready...
[2023-09-13 20:14:02 +0200] [6492] [INFO] Done.
[2023-09-13 21:00:10 +0200] [6492] [INFO] Running new executor...
[2023-09-13 21:00:10 +0200] [6492] [INFO] Execution options: {}
[2023-09-13 21:00:10 +0200] [6492] [ERROR] 'FreeTypeFont' object has no attribute 'getsize'
Traceback (most recent call last):
  File "C:\Users\micha\Git\chaiNNer\backend\src\process.py", line 106, in run_node
    raw_output = node.run(*enforced_inputs)
  File "C:\Users\micha\Git\chaiNNer\backend\src\packages\chaiNNer_standard\image\create_images\text_as_image.py", line 173, in text_as_image_node
    w_ref, h_ref = font.getsize(max_line)[0], font.getsize("[�]")[1]
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\micha\Git\chaiNNer\backend\src\server.py", line 189, in run
    await executor.run()
  File "C:\Users\micha\Git\chaiNNer\backend\src\process.py", line 576, in run
    await self.__process_nodes(self.__get_output_nodes())
  File "C:\Users\micha\Git\chaiNNer\backend\src\process.py", line 563, in __process_nodes
    await self.process(output_node)
  File "C:\Users\micha\Git\chaiNNer\backend\src\process.py", line 389, in process
    return await self.__process(node)
  File "C:\Users\micha\Git\chaiNNer\backend\src\process.py", line 418, in __process
    processed_input = await self.process(node_input.id)
  File "C:\Users\micha\Git\chaiNNer\backend\src\process.py", line 389, in process
    return await self.__process(node)
  File "C:\Users\micha\Git\chaiNNer\backend\src\process.py", line 444, in __process
    output, execution_time = await self.loop.run_in_executor(
  File "C:\Python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\micha\Git\chaiNNer\backend\src\process.py", line 325, in wrapper
    result = supplier()
  File "C:\Users\micha\Git\chaiNNer\backend\src\process.py", line 115, in run_node
    raise NodeExecutionError(node_id, node, str(e), input_dict) from e
process.NodeExecutionError: 'FreeTypeFont' object has no attribute 'getsize'
[2023-09-13 21:00:10 +0200] [6492] [ERROR] Traceback (most recent call last):
  File "C:\Users\micha\Git\chaiNNer\backend\src\process.py", line 106, in run_node
    raw_output = node.run(*enforced_inputs)
  File "C:\Users\micha\Git\chaiNNer\backend\src\packages\chaiNNer_standard\image\create_images\text_as_image.py", line 173, in text_as_image_node
    w_ref, h_ref = font.getsize(max_line)[0], font.getsize("[�]")[1]
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\micha\Git\chaiNNer\backend\src\server.py", line 189, in run
    await executor.run()
  File "C:\Users\micha\Git\chaiNNer\backend\src\process.py", line 576, in run
    await self.__process_nodes(self.__get_output_nodes())
  File "C:\Users\micha\Git\chaiNNer\backend\src\process.py", line 563, in __process_nodes
    await self.process(output_node)
  File "C:\Users\micha\Git\chaiNNer\backend\src\process.py", line 389, in process
    return await self.__process(node)
  File "C:\Users\micha\Git\chaiNNer\backend\src\process.py", line 418, in __process
    processed_input = await self.process(node_input.id)
  File "C:\Users\micha\Git\chaiNNer\backend\src\process.py", line 389, in process
    return await self.__process(node)
  File "C:\Users\micha\Git\chaiNNer\backend\src\process.py", line 444, in __process
    output, execution_time = await self.loop.run_in_executor(
  File "C:\Python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\micha\Git\chaiNNer\backend\src\process.py", line 325, in wrapper
    result = supplier()
  File "C:\Users\micha\Git\chaiNNer\backend\src\process.py", line 115, in run_node
    raise NodeExecutionError(node_id, node, str(e), input_dict) from e
process.NodeExecutionError: 'FreeTypeFont' object has no attribute 'getsize'
```

</details>

**Comment by RunDevelopment** [comment]
Okay, I figured it out. I recently installed PIL v10 to test something. v10 apparently removed the `getsize` function.

![image](https://github.com/chaiNNer-org/chaiNNer/assets/20878432/c69b8f9f-beaf-4c0c-b51a-0bf0687aafb1)

[Here's the changelog of the 10.0.0 release](https://pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html#font-size-and-offset-methods). We should probably just use `getbbox`.

**Comment by RunDevelopment** [comment]
Sorry for the ping @adegerard. I should have investigated a bit further before opening this issue.

**Comment by adegerard** [comment]
> Sorry for the ping @adegerard. I should have investigated a bit further before opening this issue.
Just read this, thanks for your investigation!
my pillow version for chaiNNer was 9.2.0 and I did not read the deprecation doc.
