### ISSUE TITLE
Fails to start

### ISSUE THREAD

**Issue by geoff-m** [chaiNNer-org/chaiNNer#2607]
**Information:**

- Chainner version: 0.22.0-portable
- OS: Windows 11
**Description**
1. Download and unzip `chaiNNer-win32-x64-0.22.0-portable.zip` from Releases page.
2. Run chaiNNer.exe

Output:
```
23:04:00.633 > chaiNNer Version: 0.22.0
23:04:00.652 > Attempting to check for a port...
23:04:00.670 > Port found: 8000
23:04:00.674 > Attempting to check Python env...
[30864:0223/230400.678:ERROR:gpu_process_host.cc(948)] GPU process launch failed: error_code=18
[30864:0223/230400.710:ERROR:gpu_process_host.cc(948)] GPU process launch failed: error_code=18
[30864:0223/230400.717:ERROR:gpu_process_host.cc(948)] GPU process launch failed: error_code=18
[30864:0223/230400.749:ERROR:gpu_process_host.cc(948)] GPU process launch failed: error_code=18
23:04:00.756 > Integrated Python not found at S:\chaiNNer-win32-x64-0.22.0-portable\python\python\python.exe
23:04:00.759 > Downloading integrated Python...
[30864:0223/230400.763:ERROR:gpu_process_host.cc(948)] GPU process launch failed: error_code=18
[30864:0223/230400.766:ERROR:gpu_process_host.cc(948)] GPU process launch failed: error_code=18
[30864:0223/230400.766:FATAL:gpu_data_manager_impl_private.cc(431)] GPU process isn't usable. Goodbye.
```

[main.log](https://github.com/chaiNNer-org/chaiNNer/files/14392028/main.log)

**Comment by joeyballentine** [comment]
1) what GPU do you have?
2) are your drivers up to date?

**Comment by geoff-m** [comment]
1. Nvidia RTX 3080 (10 GB).
2. Yes.

**Comment by Codinablack** [comment]
Just for clarification, runs fine on my system, which is windows 10 22h2 with radeon 6400

**Comment by geoff-m** [comment]
Very clear, I'll be right over to use it!

**Comment by joeyballentine** [comment]
Do any other electron based apps work on your computer? Such as discord or slack?

**Comment by geoff-m** [comment]
Yes, both of those do.

**Comment by scrawfor** [comment]
3060ti similar issue.  First boot was succesful, subsequent boots don't display any UI. 

Error snippet from log


```log
ImportError: cannot import name 'NotRequired' from 'typing_extensions' (D:\Programs\chaiNNer-win32-x64-0.22.0-portable\python\python\Lib\site-packages\typing_extensions.py)
[2024-02-26 21:11:27.912] [info]  Backend: [1340] [WARNING] Failed to load packages.chaiNNer_external.external_stable_diffusion.automatic1111.text_to_image (D:\Programs\chaiNNer-win32-x64-0.22.0-portable\resources\src\packages\chaiNNer_external\external_stable_diffusion\automatic1111\text_to_image.py):
Traceback (most recent call last):
  File "D:\Programs\chaiNNer-win32-x64-0.22.0-portable\resources\src\api\api.py", line 396, in load_nodes
    importlib.import_module(module, package=None)
  File "D:\Programs\chaiNNer-win32-x64-0.22.0-portable\python\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Programs\chaiNNer-win32-x64-0.22.0-portable\resources\src\packages\chaiNNer_external\external_stable_diffusion\automatic1111\text_to_image.py", line 7, in <module>
    from nodes.properties.inputs import (
  File "D:\Programs\chaiNNer-win32-x64-0.22.0-portable\resources\src\nodes\properties\inputs\__init__.py", line 2, in <module>
    from .generic_inputs import *
  File "D:\Programs\chaiNNer-win32-x64-0.22.0-portable\resources\src\nodes\properties\inputs\generic_inputs.py", line 11, in <module>
    from typing_extensions import NotRequired
ImportError: cannot import name 'NotRequired' from 'typing_extensions' (D:\Programs\chaiNNer-win32-x64-0.22.0-portable\python\python\Lib\site-packages\typing_extensions.py)
[2024-02-26 21:11:27.921] [info]  Backend: [1340] [WARNING] Failed to load packages.chaiNNer_external.external_stable_diffusion.automatic1111.upscale (D:\Programs\chaiNNer-win32-x64-0.22.0-portable\resources\src\packages\chaiNNer_external\external_stable_diffusion\automatic1111\upscale.py):
Traceback (most recent call last):
  File "D:\Programs\chaiNNer-win32-x64-0.22.0-portable\resources\src\api\api.py", line 396, in load_nodes
    importlib.import_module(module, package=None)
  File "D:\Programs\chaiNNer-win32-x64-0.22.0-portable\python\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Programs\chaiNNer-win32-x64-0.22.0-portable\resources\src\packages\chaiNNer_external\external_stable_diffusion\automatic1111\upscale.py", line 9, in <module>
    from nodes.properties.inputs import (
  File "D:\Programs\chaiNNer-win32-x64-0.22.0-portable\resources\src\nodes\properties\inputs\__init__.py", line 2, in <module>
    from .generic_inputs import *
  File "D:\Programs\chaiNNer-win32-x64-0.22.0-portable\resources\src\nodes\properties\inputs\generic_inputs.py", line 11, in <module>
    from typing_extensions import NotRequired
ImportError: cannot import name 'NotRequired' from 'typing_extensions' (D:\Programs\chaiNNer-win32-x64-0.22.0-portable\python\python\Lib\site-packages\typing_extensions.py)
[2024-02-26 21:11:27 -0500] [1340] [WARNING] Failed to import 14 modules:
[2024-02-26 21:11:27.922] [info]  Backend: [1340] [WARNING] No module named 'spandrel'  ->  packages.chaiNNer_pytorch.pytorch.io.load_model
```

**Comment by joeyballentine** [comment]
@scrawfor that issue is unrelated to your GPU. It looks like some dependencies failed to install. Since that's a portable build, my recommendation would be to delete the python folder at chaiNNer's root and then start chaiNNer up again. Let me know if that continues to happen

**Comment by scrawfor** [comment]
Ah, you're right.  Just looked at his title and assumed it was the same issue. Missed his log.  Reinstalling worked.

Sorry for the spam. I'll delete my message since it's irrelevant.

**Comment by joeyballentine** [comment]
All good, glad it's working now
