### ISSUE TITLE
Save Video Node "An iterator output was not assigned correctly"

### ISSUE THREAD

**Issue by Multiboxer** [chaiNNer-org/chaiNNer#2817]
**Information:**

- Chainner version: [Alpha v0.23.2]
- OS: [Windows 11 64 bit]

**Description**
As of [Alpha v0.23.2] an error is output when attempting to use a "save video" module via any input node method. Logs below show a "load video" -> "save video" error message.

**Logs**
An error occurred in a Save Video node:

An iterator output was not assigned correctly

Input values:
• Image Sequence: *unknown*
• Directory: *unknown*
• Video Name: *unknown*
• Video Format: *unknown*
• Encoder: *unknown*
• Video Preset: *unknown*
• Quality (CRF): *unknown*
• Additional parameters: *unknown*
• Additional parameters: *unknown*
• FPS: *unknown*
• Audio Stream: *unknown*
• Audio: *unknown*

Stack TraceTraceback (most recent call last):
  File "C:\Users\user\AppData\Local\chaiNNer\app-0.23.2\resources\src\process.py", line 415, in process
    return await self.__process(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\chaiNNer\app-0.23.2\resources\src\process.py", line 563, in __process
    inputs = await self.__gather_inputs(node)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\chaiNNer\app-0.23.2\resources\src\process.py", line 519, in __gather_inputs
    inputs.append(await self.__resolve_node_input(node_input))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\chaiNNer\app-0.23.2\resources\src\process.py", line 481, in __resolve_node_input
    return await self.__get_node_output(node_input.id, node_input.index)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\chaiNNer\app-0.23.2\resources\src\process.py", line 471, in __get_node_output
    assert value is not None, "An iterator output was not assigned correctly"
           ^^^^^^^^^^^^^^^^^
AssertionError: An iterator output was not assigned correctly

**Comment by joeyballentine** [comment]
Thanks for reporting. We will investigate
