### ISSUE TITLE
Crash/hang: Can't start chainner at al // ModuleNotFoundError: No module named 'attr'

### ISSUE THREAD

**Issue by sbrl** [chaiNNer-org/chaiNNer#3042]
**Information:**

- Chainner version: 0.24.1
- OS: Ubuntu 24.04
- `uname -a`: `Linux Starfall 6.8.0-45-generic #45-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 30 12:02:04 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
- (system) `python --version`: `Python 3.12.3`
- 

**Description**
On startup, chaiNNer claims that it is endlessly starting the backend process:

![Selection_2024-10-21_19:13:44_001_8efe592](https://github.com/user-attachments/assets/570763c8-08ce-4b93-8f1c-1033fed6f08b)

...running it in the terminal however results in a much more useful error, as described in the logs suggestion

.....this suggests that the `attr` package is missing, but I already have `python3-attr` installed (log #2).

I tried installing the `attr` package with `pip3 install attr --user --break-system-packages`, but frustratingly this did not change the error.

I did see https://github.com/chaiNNer-org/chaiNNer/issues/3010, but while may be related to this bug seems distinctly different. It does suggest that chaiNNer has it's own isolated python environment, which seems to be at fault here.

To this end, I navigated to `~/.config/chaiNNer/python/python` and manually run: `bin/chainner_pip3 install attr --verbose`, which correctly installed the package inside the environment.

This resolved the error, but resulted in another similar error ([log 3](#log-3)), which claims `ModuleNotFoundError: No module named 'idna'`.

To this end, my findings suggest that your 'isolated environment' is completely broken, and does not serve the intended purpose.

Furthermore, since you do not have a CLI flag to force chaiNNer to use the system packages one is left without a workaround in case of issues.

Full list of packages I hackily installed using the above method:

```
INSTALL attr
INSTALL idna
UNINSTALL attr
INSTALL attrs
```

...then I can start it, but the viewer node says "image not valid" or something to that effect.

Restarting with the system version of Python and applying [this workaround](https://askubuntu.com/a/1511013/139735) results in log #4.

....so I'm at a standstill here.

**Logs**

..logs provided are not from the menu provided in the issue template, because I can't start the app in the first place to check.

### Log 1
Original error:

```syslog
19:13:09.441 › Attempting to spawn backend...
19:13:10.465 › Failed to fetch features from backend: TypeError: Failed to fetch
19:13:10.925 › Backend: Traceback (most recent call last):
  File "/usr/lib/chainner/resources/src/run.py", line 7, in <module>
    server_host = importlib.import_module("server_host")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sbrl/.config/chaiNNer/python/python/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/chainner/resources/src/server_host.py", line 33, in <module>
    from server_process_helper import WorkerServer
19:13:10.927 › Backend:   File "/usr/lib/chainner/resources/src/server_process_helper.py", line 14, in <module>
    import aiohttp
  File "/home/sbrl/.local/lib/python3.11/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/home/sbrl/.local/lib/python3.11/site-packages/aiohttp/client.py", line 34, in <module>
    import attr
ModuleNotFoundError: No module named 'attr'
19:13:10.985 › Python subprocess exited with code 1 and signal null
19:13:11.470 › Failed to fetch features from backend: TypeError: Failed to fetch
19:13:13.474 › Failed to fetch features from backend: TypeError: Failed to fetch
19:13:17.478 › Failed to fetch features from backend: TypeError: Failed to fetch
19:13:25.483 › Failed to fetch features from backend: TypeError: Failed to fetch
19:13:41.487 › Failed to fetch features from backend: TypeError: Failed to fetch
19:14:11.492 › Failed to fetch features from backend: TypeError: Failed to fetch
```

### Log 2
`python3-attr` is indeed installed:

```bash
$ apt-cache policy python3-attr
python3-attr:
  Installed: 23.2.0-2
  Candidate: 23.2.0-2
  Version table:
 *** 23.2.0-2 500
        500 http://gb.archive.ubuntu.com/ubuntu noble/main amd64 Packages
        500 http://gb.archive.ubuntu.com/ubuntu noble/main i386 Packages
        100 /var/lib/dpkg/status
```

### Log 3
```syslog
$ chainner 
19:22:41.339 › chaiNNer Version: 0.24.1
19:22:41.350 › Attempting to check for a port...
19:22:41.359 › Port found: 8000
19:22:41.360 › Attempting to check integrated Python env...
[14443:1021/192241.364936:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
19:22:41.396 › Final Python binary: /home/sbrl/.config/chaiNNer/python/python/bin/python3.11
19:22:41.397 › {
  python: '/home/sbrl/.config/chaiNNer/python/python/bin/python3.11',
  version: '3.11.5'
}
19:22:41.404 › Attempting to spawn backend...
19:22:42.182 › Failed to fetch features from backend: TypeError: Failed to fetch
19:22:42.561 › Backend: Traceback (most recent call last):
  File "/usr/lib/chainner/resources/src/run.py", line 7, in <module>
    server_host = importlib.import_module("server_host")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sbrl/.config/chaiNNer/python/python/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/chainner/resources/src/server_host.py", line 33, in <module>
19:22:42.563 › Backend:     from server_process_helper import WorkerServer
  File "/usr/lib/chainner/resources/src/server_process_helper.py", line 14, in <module>
    import aiohttp
  File "/home/sbrl/.local/lib/python3.11/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/home/sbrl/.local/lib/python3.11/site-packages/aiohttp/client.py", line 36, in <module>
    from yarl import URL
  File "/home/sbrl/.local/lib/python3.11/site-packages/yarl/__init__.py", line 1, in <module>
    from ._url import URL, cache_clear, cache_configure, cache_info
  File "/home/sbrl/.local/lib/python3.11/site-packages/yarl/_url.py", line 9, in <module>
    import idna
ModuleNotFoundError: No module named 'idna'
19:22:42.653 › Python subprocess exited with code 1 and signal null
19:22:43.189 › Failed to fetch features from backend: TypeError: Failed to fetch
19:22:45.193 › Failed to fetch features from backend: TypeError: Failed to fetch
19:22:49.198 › Failed to fetch features from backend: TypeError: Failed to fetch
```

### Log 4
```bash
19:41:36.263 › Backend: [2024-10-21 19:41:36 +0100] [21520] [ERROR] Exception occurred while handling uri: 'http://127.0.0.1:8000/features'
Traceback (most recent call last):
  File "handle_request", line 97, in handle_request
    from sanic_ext.extensions.base import Extension  # type: ignore
                       ^^^^^^^^^^^^^^
  File "/usr/lib/chainner/resources/src/server_host.py", line 207, in get_features
    return await worker.proxy_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/chainner/resources/src/server_process_helper.py", line 231, in proxy_request
    async with self._session.request(
  File "/home/sbrl/.local/lib/python3.12/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/home/sbrl/.local/lib/python3.12/site-packages/aiohttp/client.py", line 425, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed
19:41:36.267 › Failed to fetch features from backend: SyntaxError: Unexpected token '⚠', "⚠️ 500 — I"... is not valid JSON
19:41:37.209 › Backend: [2024-10-21 19:41:37 +0100] [21520] [ERROR] Exception occurred while handling uri: 'http://127.0.0.1:8000/nodes'
Traceback (most recent call last):
  File "handle_request", line 97, in handle_request
    from sanic_ext.extensions.base import Extension  # type: ignore
                       ^^^^^^^^^^^^^^
  File "/usr/lib/chainner/resources/src/server_host.py", line 95, in nodes
    return await worker.proxy_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/chainner/resources/src/server_process_helper.py", line 231, in proxy_request
    async with self._session.request(
  File "/home/sbrl/.local/lib/python3.12/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/home/sbrl/.local/lib/python3.12/site-packages/aiohttp/client.py", line 425, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed
19:41:37.212 › Backend: [2024-10-21 19:41:37 +0100] [21520] [ERROR] Exception occurred while handling uri: 'http://127.0.0.1:8000/packages'
Traceback (most recent call last):
  File "handle_request", line 97, in handle_request
    from sanic_ext.extensions.base import Extension  # type: ignore
                       ^^^^^^^^^^^^^^
  File "/usr/lib/chainner/resources/src/server_host.py", line 187, in get_packages
    return await worker.proxy_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/chainner/resources/src/server_process_helper.py", line 231, in proxy_request
    async with self._session.request(
  File "/home/sbrl/.local/lib/python3.12/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/home/sbrl/.local/lib/python3.12/site-packages/aiohttp/client.py", line 425, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed
19:41:37.215 › Failed to fetch nodes from backend: SyntaxError: Unexpected token '⚠', "⚠️ 500 — I"... is not valid JSON
19:41:37.217 › Failed to fetch packages from backend: SyntaxError: Unexpected token '⚠', "⚠️ 500 — I"... is not valid JSON
19:41:38.221 › Backend: [2024-10-21 19:41:38 +0100] [21520] [ERROR] Exception occurred while handling uri: 'http://127.0.0.1:8000/nodes'
Traceback (most recent call last):
  File "handle_request", line 97, in handle_request
    from sanic_ext.extensions.base import Extension  # type: ignore
                       ^^^^^^^^^^^^^^
  File "/usr/lib/chainner/resources/src/server_host.py", line 95, in nodes
    return await worker.proxy_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/chainner/resources/src/server_process_helper.py", line 231, in proxy_request
    async with self._session.request(
  File "/home/sbrl/.local/lib/python3.12/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/home/sbrl/.local/lib/python3.12/site-packages/aiohttp/client.py", line 425, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed
19:41:38.222 › Backend: [2024-10-21 19:41:38 +0100] [21520] [ERROR] Exception occurred while handling uri: 'http://127.0.0.1:8000/packages'
Traceback (most recent call last):
  File "handle_request", line 97, in handle_request
    from sanic_ext.extensions.base import Extension  # type: ignore
                       ^^^^^^^^^^^^^^
  File "/usr/lib/chainner/resources/src/server_host.py", line 187, in get_packages
    return await worker.proxy_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/chainner/resources/src/server_process_helper.py", line 231, in proxy_request
    async with self._session.request(
  File "/home/sbrl/.local/lib/python3.12/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/home/sbrl/.local/lib/python3.12/site-packages/aiohttp/client.py", line 425, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed
19:41:38.225 › Failed to fetch nodes from backend: SyntaxError: Unexpected token '⚠', "⚠️ 500 — I"... is not valid JSON
19:41:38.227 › Failed to fetch packages from backend: SyntaxError: Unexpected token '⚠', "⚠️ 500 — I"... is not valid JSON
19:41:40.231 › Backend: [2024-10-21 19:41:40 +0100] [21520] [ERROR] Exception occurred while handling uri: 'http://127.0.0.1:8000/nodes'
Traceback (most recent call last):
  File "handle_request", line 97, in handle_request
    from sanic_ext.extensions.base import Extension  # type: ignore
                       ^^^^^^^^^^^^^^
  File "/usr/lib/chainner/resources/src/server_host.py", line 95, in nodes
    return await worker.proxy_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/chainner/resources/src/server_process_helper.py", line 231, in proxy_request
    async with self._session.request(
  File "/home/sbrl/.local/lib/python3.12/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/home/sbrl/.local/lib/python3.12/site-packages/aiohttp/client.py", line 425, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed
19:41:40.233 › Backend: [2024-10-21 19:41:40 +0100] [21520] [ERROR] Exception occurred while handling uri: 'http://127.0.0.1:8000/packages'
Traceback (most recent call last):
  File "handle_request", line 97, in handle_request
    from sanic_ext.extensions.base import Extension  # type: ignore
                       ^^^^^^^^^^^^^^
  File "/usr/lib/chainner/resources/src/server_host.py", line 187, in get_packages
    return await worker.proxy_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/chainner/resources/src/server_process_helper.py", line 231, in proxy_request
    async with self._session.request(
  File "/home/sbrl/.local/lib/python3.12/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/home/sbrl/.local/lib/python3.12/site-packages/aiohttp/client.py", line 425, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed
19:41:40.238 › Failed to fetch packages from backend: SyntaxError: Unexpected token '⚠', "⚠️ 500 — I"... is not valid JSON
19:41:40.239 › Failed to fetch nodes from backend: SyntaxError: Unexpected token '⚠', "⚠️ 500 — I"... is not valid JSON
19:41:44.241 › Backend: [2024-10-21 19:41:44 +0100] [21520] [ERROR] Exception occurred while handling uri: 'http://127.0.0.1:8000/nodes'
Traceback (most recent call last):
  File "handle_request", line 97, in handle_request
    from sanic_ext.extensions.base import Extension  # type: ignore
                       ^^^^^^^^^^^^^^
  File "/usr/lib/chainner/resources/src/server_host.py", line 95, in nodes
    return await worker.proxy_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/chainner/resources/src/server_process_helper.py", line 231, in proxy_request
    async with self._session.request(
  File "/home/sbrl/.local/lib/python3.12/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/home/sbrl/.local/lib/python3.12/site-packages/aiohttp/client.py", line 425, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed
19:41:44.242 › Backend: [2024-10-21 19:41:44 +0100] [21520] [ERROR] Exception occurred while handling uri: 'http://127.0.0.1:8000/packages'
Traceback (most recent call last):
  File "handle_request", line 97, in handle_request
    from sanic_ext.extensions.base import Extension  # type: ignore
                       ^^^^^^^^^^^^^^
  File "/usr/lib/chainner/resources/src/server_host.py", line 187, in get_packages
    return await worker.proxy_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/chainner/resources/src/server_process_helper.py", line 231, in proxy_request
    async with self._session.request(
  File "/home/sbrl/.local/lib/python3.12/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/home/sbrl/.local/lib/python3.12/site-packages/aiohttp/client.py", line 425, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed
19:41:44.243 › Failed to fetch nodes from backend: SyntaxError: Unexpected token '⚠', "⚠️ 500 — I"... is not valid JSON
19:41:44.244 › Failed to fetch packages from backend: SyntaxError: Unexpected token '⚠', "⚠️ 500 — I"... is not valid JSON
19:41:52.251 › Backend: [2024-10-21 19:41:52 +0100] [21520] [ERROR] Exception occurred while handling uri: 'http://127.0.0.1:8000/packages'
Traceback (most recent call last):
  File "handle_request", line 97, in handle_request
    from sanic_ext.extensions.base import Extension  # type: ignore
                       ^^^^^^^^^^^^^^
  File "/usr/lib/chainner/resources/src/server_host.py", line 187, in get_packages
    return await worker.proxy_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/chainner/resources/src/server_process_helper.py", line 231, in proxy_request
    async with self._session.request(
  File "/home/sbrl/.local/lib/python3.12/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/home/sbrl/.local/lib/python3.12/site-packages/aiohttp/client.py", line 425, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed
19:41:52.254 › Backend: [2024-10-21 19:41:52 +0100] [21520] [ERROR] Exception occurred while handling uri: 'http://127.0.0.1:8000/nodes'
Traceback (most recent call last):
  File "handle_request", line 97, in handle_request
    from sanic_ext.extensions.base import Extension  # type: ignore
                       ^^^^^^^^^^^^^^
  File "/usr/lib/chainner/resources/src/server_host.py", line 95, in nodes
    return await worker.proxy_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/chainner/resources/src/server_process_helper.py", line 231, in proxy_request
    async with self._session.request(
  File "/home/sbrl/.local/lib/python3.12/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/home/sbrl/.local/lib/python3.12/site-packages/aiohttp/client.py", line 425, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed
19:41:52.323 › Failed to fetch nodes from backend: SyntaxError: Unexpected token '⚠', "⚠️ 500 — I"... is not valid JSON
19:41:52.324 › Failed to fetch packages from backend: SyntaxError: Unexpected token '⚠', "⚠️ 500 — I"... is not valid JSON
19:41:52.330 › Backend: [2024-10-21 19:41:52 +0100] [21520] [ERROR] Exception occurred while handling uri: 'http://127.0.0.1:8000/features'
Traceback (most recent call last):
  File "handle_request", line 97, in handle_request
    from sanic_ext.extensions.base import Extension  # type: ignore
                       ^^^^^^^^^^^^^^
  File "/usr/lib/chainner/resources/src/server_host.py", line 207, in get_features
    return await worker.proxy_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/chainner/resources/src/server_process_helper.py", line 231, in proxy_request
    async with self._session.request(
  File "/home/sbrl/.local/lib/python3.12/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/home/sbrl/.local/lib/python3.12/site-packages/aiohttp/client.py", line 425, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed
19:41:52.333 › Failed to fetch features from backend: SyntaxError: Unexpected token '⚠', "⚠️ 500 — I"... is not valid JSON
19:42:08.331 › Backend: [2024-10-21 19:42:08 +0100] [21520] [ERROR] Exception occurred while handling uri: 'http://127.0.0.1:8000/nodes'
Traceback (most recent call last):
  File "handle_request", line 97, in handle_request
    from sanic_ext.extensions.base import Extension  # type: ignore
                       ^^^^^^^^^^^^^^
  File "/usr/lib/chainner/resources/src/server_host.py", line 95, in nodes
    return await worker.proxy_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/chainner/resources/src/server_process_helper.py", line 231, in proxy_request
    async with self._session.request(
  File "/home/sbrl/.local/lib/python3.12/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/home/sbrl/.local/lib/python3.12/site-packages/aiohttp/client.py", line 425, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed
19:42:08.333 › Backend: [2024-10-21 19:42:08 +0100] [21520] [ERROR] Exception occurred while handling uri: 'http://127.0.0.1:8000/packages'
Traceback (most recent call last):
  File "handle_request", line 97, in handle_request
    from sanic_ext.extensions.base import Extension  # type: ignore
                       ^^^^^^^^^^^^^^
  File "/usr/lib/chainner/resources/src/server_host.py", line 187, in get_packages
    return await worker.proxy_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/chainner/resources/src/server_process_helper.py", line 231, in proxy_request
    async with self._session.request(
  File "/home/sbrl/.local/lib/python3.12/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/home/sbrl/.local/lib/python3.12/site-packages/aiohttp/client.py", line 425, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed
19:42:08.391 › Failed to fetch nodes from backend: SyntaxError: Unexpected token '⚠', "⚠️ 500 — I"... is not valid JSON
19:42:08.395 › Failed to fetch packages from backend: SyntaxError: Unexpected token '⚠', "⚠️ 500 — I"... is not valid JSON
```

**Comment by Florian9M** [comment]
It seems to be a similar problem. I tried running chaiNNer locally, and after following the steps from the "Contributing" documentation (`npm ci `and `pip install -r requirements.txt`), I encountered the following error.
OS: WIndows

Python version: 3.11.9

```
(venv) C:\Users\flori\Documents\experimentations\tests\chaiNNer>python ./backend/src/run.py --close-after-start --install-builtin-packages
[2025-05-14 15:23:47 +0200] [18104] [INFO]
  ┌─────────────────────────────────────────────────────────────┐
  │                        Sanic v23.3.0                        │
  │              Goin' Fast @ http://127.0.0.1:8000             │
  ├───────────────────────┬─────────────────────────────────────┤
  │                       │     mode: production, single worker │
  │     ▄███ █████ ██     │   server: sanic, HTTP/1.1           │
  │    ██                 │   python: 3.11.9                    │
  │     ▀███████ ███▄     │ platform: Windows-10-10.0.26100-SP0 │
  │                 ██    │ packages: sanic-routing==22.8.0     │
  │    ████ ████████▀     │                                     │
  │                       │                                     │
  │ Build Fast. Run Fast. │                                     │
  └───────────────────────┴─────────────────────────────────────┘

[2025-05-14 15:23:47 +0200] [18104] [WARNING] Sanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.
[2025-05-14 15:23:47 +0200] [18104] [INFO] Starting worker process on port 62163...
[2025-05-14 15:23:48 +0200] [18104] [INFO] [Worker] Sanic v23.3.0
[2025-05-14 15:23:48 +0200] [18104] [INFO] [Worker] Goin' Fast @ http://127.0.0.1:62163
[2025-05-14 15:23:48 +0200] [18104] [INFO] [Worker] mode: production, single worker
[2025-05-14 15:23:48 +0200] [18104] [INFO] [Worker] server: sanic, HTTP/1.1
[2025-05-14 15:23:48 +0200] [18104] [INFO] [Worker] python: 3.11.9
[2025-05-14 15:23:48 +0200] [18104] [INFO] [Worker] platform: Windows-10-10.0.26100-SP0
[2025-05-14 15:23:48 +0200] [18104] [INFO] [Worker] packages: sanic-routing==22.8.0
[2025-05-14 15:23:48 +0200] [18104] [INFO] [Worker] Loading Nodes...
[2025-05-14 15:23:49 +0200] [18104] [WARNING] [Worker] Failed to import 25 modules:
[2025-05-14 15:23:49 +0200] [18104] [WARNING] [Worker] No module named 'ncnn'  ->  3 modules ...
[2025-05-14 15:23:49 +0200] [18104] [INFO] [Worker]   ->  packages.chaiNNer_ncnn.settings
[2025-05-14 15:23:49 +0200] [18104] [INFO] [Worker]   ->  packages.chaiNNer_ncnn.ncnn.processing.upscale_image
[2025-05-14 15:23:49 +0200] [18104] [INFO] [Worker]   ->  packages.chaiNNer_ncnn.ncnn.utility.interpolate_models
[2025-05-14 15:23:49 +0200] [18104] [WARNING] [Worker] No module named 'onnx'  ->  5 modules ...
[2025-05-14 15:23:49 +0200] [18104] [INFO] [Worker]   ->  packages.chaiNNer_onnx.onnx.batch_processing.load_models
[2025-05-14 15:23:49 +0200] [18104] [INFO] [Worker]   ->  packages.chaiNNer_onnx.onnx.io.load_model
[2025-05-14 15:23:49 +0200] [18104] [INFO] [Worker]   ->  and 3 more ...
[2025-05-14 15:23:49 +0200] [18104] [WARNING] [Worker] No module named 'onnxruntime'  ->  3 modules ...
[2025-05-14 15:23:49 +0200] [18104] [INFO] [Worker]   ->  packages.chaiNNer_onnx.settings
[2025-05-14 15:23:49 +0200] [18104] [INFO] [Worker]   ->  packages.chaiNNer_onnx.onnx.processing.remove_background
[2025-05-14 15:23:49 +0200] [18104] [INFO] [Worker]   ->  packages.chaiNNer_onnx.onnx.processing.upscale_image
[2025-05-14 15:23:49 +0200] [18104] [WARNING] [Worker] No module named 'spandrel'  ->  4 modules ...
[2025-05-14 15:23:49 +0200] [18104] [INFO] [Worker]   ->  packages.chaiNNer_pytorch.pytorch.io.load_model
[2025-05-14 15:23:49 +0200] [18104] [INFO] [Worker]   ->  packages.chaiNNer_pytorch.pytorch.iteration.load_models
[2025-05-14 15:23:49 +0200] [18104] [INFO] [Worker]   ->  and 2 more ...
[2025-05-14 15:23:49 +0200] [18104] [WARNING] [Worker] No module named 'torch'  ->  10 modules ...
[2025-05-14 15:23:49 +0200] [18104] [INFO] [Worker]   ->  packages.chaiNNer_pytorch.settings
[2025-05-14 15:23:49 +0200] [18104] [INFO] [Worker]   ->  packages.chaiNNer_pytorch.pytorch.io.save_model
[2025-05-14 15:23:49 +0200] [18104] [INFO] [Worker]   ->  and 8 more ...
[2025-05-14 15:23:49 +0200] [18104] [INFO] [Worker] Starting worker [1656]
[2025-05-14 15:23:49 +0200] [18104] [INFO] Worker process started
[2025-05-14 15:23:49 +0200] [18104] [INFO] Starting setup...
[2025-05-14 15:23:49 +0200] [18104] [INFO] Closing server...
[2025-05-14 15:23:49 +0200] [18104] [INFO] Starting worker [18104]
[2025-05-14 15:23:52 +0200] [18104] [INFO] Importing nodes...
[2025-05-14 15:23:52 +0200] [18104] [INFO] Checking dependencies...
[2025-05-14 15:23:52 +0200] [18104] [INFO] Checking dependencies for chaiNNer_standard...
[2025-05-14 15:23:52 +0200] [18104] [INFO] Checking dependencies for PyTorch...
[2025-05-14 15:23:52 +0200] [18104] [INFO] Checking dependencies for NCNN...
[2025-05-14 15:23:52 +0200] [18104] [INFO] Checking dependencies for ONNX...
[2025-05-14 15:23:52 +0200] [18104] [INFO] Checking dependencies for External...
[2025-05-14 15:23:52 +0200] [18104] [INFO] Closing worker process...
[2025-05-14 15:23:52 +0200] [18104] [INFO] Worker process stopped
[2025-05-14 15:23:52 +0200] [18104] [INFO] Stopped reading worker stdout due to stdout ending
[2025-05-14 15:23:52 +0200] [18104] [INFO] Stopped reading worker stderr due to stderr ending
[2025-05-14 15:23:52 +0200] [18104] [INFO] Looking in indexes: https://pypi.org/simple, https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/,https://download.pytorch.org/whl/cu121
[2025-05-14 15:23:53 +0200] [18104] [INFO] ERROR: Could not find a version that satisfies the requirement torch==2.1.2+cu121 (from versions: 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 2.5.0, 2.5.1, 2.6.0, 2.7.0)
[2025-05-14 15:23:53 +0200] [18104] [INFO] ERROR: No matching distribution found for torch==2.1.2+cu121
[2025-05-14 15:23:53 +0200] [18104] [ERROR] Error installing dependencies: An error occurred while installing dependencies.
Traceback (most recent call last):
  File "C:\Users\flori\Documents\experimentations\tests\chaiNNer\backend\src\server_host.py", line 424, in import_packages
    await install_dependencies(deps_to_install, update_progress_cb, logger)
  File "C:\Users\flori\Documents\experimentations\tests\chaiNNer\backend\src\dependencies\store.py", line 234, in install_dependencies
    raise ValueError("An error occurred while installing dependencies.")
ValueError: An error occurred while installing dependencies.
[2025-05-14 15:23:53 +0200] [18104] [ERROR] Error waiting for server to start: Error installing dependencies
[2025-05-14 15:23:53 +0200] [18104] [INFO] Worker process stopped
[2025-05-14 15:23:53 +0200] [18104] [INFO] Stopping worker [18104]
[2025-05-14 15:23:53 +0200] [18104] [INFO] Worker process stopped
[2025-05-14 15:23:53 +0200] [18104] [INFO] Server closed.
[2025-05-14 15:23:53 +0200] [18104] [INFO] Server Stopped
Task was destroyed but it is pending!
task: <Task pending name='Task-4' coro=<ctrlc_workaround_for_windows.<locals>.stay_active() done, defined at C:\Users\flori\Documents\experimentations\tests\chaiNNer\venv\Lib\site-packages\sanic\compat.py:125> wait_for=<Future pending cb=[Task.task_wakeup()]>>

```
