### ISSUE TITLE
same config - GUI works well, cli version breaks

### ISSUE THREAD

**Issue by abcnorio** [chaiNNer-org/chaiNNer#3066]
### Environment

chainner = v0.24.1 from release page (zip, not deb)
OS = debian trixie
GPU = nvidia 4090

### Behaviour

- config runs perfectly fine in GUI
- config does not run with `chainner run [config]` - see attached log

### Previously done

- saved config in GUI
- replaced paths with `sed` under linux on the terminal

### Expected behavior

- it should run, because only paths were changed and this is essential for scripting the cli version over different models with varying image folders and different text append
- the GUI complains that the config was changed, but runs without any problem - see log that it runs, tried that several times, no break
- the cli version breaks - see log

AGAIN:

- same config (!!!) ie. 100% identical

### Additional question

- What is the proper way to change paths in a `.chn` config for cli scripting on the terminal? This is essential to be able to change paths and it does not touch or change any nodes. Insofar the explanations on the webpage for cli configs do not seem to be relevant. But nevertheless chainner complains about a changed config that only contains changed paths, nothing else.

Thanks!

### LOGS

file:///home/leo/library/GP_project/GP_chainner_cli-R/chainneroutput_TEST1-sed3_chainner_model-images-upscale_v1_GP-chainnersaved.zip
file:///home/leo/library/GP_project/GP_chainner_cli-R/GUI-works-in-contrast-to-cli-same-config_chainner_main.zip
file:///home/leo/library/GP_project/GP_chainner_cli-R/chainner_cli-error.zip

**Comment by derek-yn-zhang** [comment]
I have a similar issue where a workflow runs without issues in the GUI, but breaks when I run it using the CLI.

## Environment
chaiNNer =  v0.24.1
OS = macOS Sequoia 15.1.1
GPU = Apple M4 Pro

## Behavior
Workflow runs without issues in the GUI
Workflow breaks with CLI command using override option -- see attached log

## Expected behavior
The CLI command should work the same way as the GUI, and successfully execute the workflow. I examined logs from the GUI runs, and the error that breaks the CLI version is also present there -- it just doesn't seem to matter.

## Logs
[chainner_cli_error.log](https://github.com/user-attachments/files/18393001/chainner_cli_error.log)
[upscale_chain.chn.zip](https://github.com/user-attachments/files/18393009/upscale_chain.chn.zip)

Thanks for looking into it!

**Comment by wbjaypo** [comment]
### Environment
chaiNNer = v0.24.1 (deb from github release)
OS = Ubuntu 24.04.1
GPU = nVidia GRiD L40-48Q

I have tested both 'sudo' with appropriate xhost +SI and "headless" using xvfb-run.

### (Expected) Behaviour
Per previous reports, `chainner open <file>` and clicking play works. `chainner run <file>` does not.

"Watching" the UI, sometimes the control buttons in the header will seemingly switch to a "paused" state (ie "Play" lit, pause and stop disabled, the "LOAD VIDEO" node will have a checkmark instead of the spinner, then it goes back to being a spinner, pause/stop will be lit and play will be disabled), then it picks up from the last Frame Index and keeps going.

`chainner open` the console output is "silent", however `chainner run` seems to output the following before it dies (apologies if back tick messes up the newlines):
`19:51:18.820 › TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at async c_.fetchJson (/usr/lib/chainner/resources/app/.vite/build/main.js:79:2252)
    at async MrA (/usr/lib/chainner/resources/app/.vite/build/main.js:703:1267)
19:51:18.821 › Cleaning up temp folders...`

I wouldn't even know where to start looking in the code but it kind of feels like a buffer empty/underrun and a race condition that sorts itself out when the GUI is running.
